### ISSUE TITLE
Velero helm chart not found when set as dependency

### ISSUE THREAD

**Issue by RomanPanaget** [vmware-tanzu/helm-charts#113]
Hi, I'm currently trying to implement my own backup chart by firstly setting velero as a chart dependency. Somehow I am not able to board it as a dependency, I can only install it with `helm install`

Here's my `Chart.yaml`:

```
apiVersion: v2
name: backups
description: A Helm chart for backups

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.4.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

dependencies: 
  - name: vmware-tanzu/velero
    version: 2.12.0
    repository: https://vmware-tanzu.github.io/helm-charts
```

When I execute `helm dep build`or `helm dep update` I get this error:

```
Error: vmware-tanzu/velero chart not found in repo https://vmware-tanzu.github.io/helm-charts
```

**Comment by Morzain** [comment]
I was running into an issue with this as well, and had to set the name to just 'velero'

**Comment by carlisia** [comment]
Hi @RomanPanaget, I haven't used a chart as a dependency. I wonder if you are still having this issue?

**Comment by RomanPanaget** [comment]
I tried just `velero` and other combinations without any luck. Might be solved today, haven't tried again since I opened this issue. Let's keep it open until someone can confirm it is solved or not just in case this is still a genuine issue

**Comment by jenting** [comment]
Hi @RomanPanaget, I read the helm doc https://helm.sh/docs/topics/charts/#chart-dependencies and I think using the name `velero` is correct because helm would search `velero` under URL `https://vmware-tanzu.github.io/helm-charts`.

Or you could use the name of the repo instead of URL.
```
$ helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
```

And in `Chart.yaml`:
```
dependencies:
  - name: velero
    version: 2.12.0
    repository: "@vmware-tanzu"
```
