### ISSUE TITLE
Helm2 upgrade to v2.12.15 failed

### ISSUE THREAD

**Issue by namm2** [vmware-tanzu/helm-charts#151]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
- Create an EKS cluster v1.15
- Install Velero Helm chart
```
helm upgrade --install velero ./velero --namespace velero -f ./values.yaml
```

Helm overriden values.yaml file:
```yaml
configuration:
  provider: aws
  volumeSnapshotLocation:
    config:
      region: eu-central-1
  backupStorageLocation:
    region: eu-central-1
    bucket: velero-backup-xxx
    config:
      region: eu-central-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws
    volumeMounts:
      - mountPath: /target
        name: plugins

schedules:
  backup-k8s:
    schedule: "*/30 * * * *"
    template:
      ttl: "72h"
      includeClusterResources: true
      snapshotVolumes: false
```

**What did you expect to happen:**
Velero helm chart installed successfully

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
```
Release "velero" does not exist. Installing it now.
Error: validation failed: unable to recognize "": no matches for kind "Schedule" in version "velero.io/v1"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): v2.16.1
- helm chart version and app version:
  - helm2 (use `helm list`): v2.12.15
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`): v1.15
- Kubernetes installer & version:
- Cloud provider or hardware configuration: EKS
- OS (e.g. from `/etc/os-release`):
