### ISSUE TITLE
Schedules are not created with Helm 2.16.1

### ISSUE THREAD

**Issue by airwalk225** [vmware-tanzu/helm-charts#160]
**What steps did you take and what happened:**
- Installing via Helm 2.16.1 via tiller into EKS k8s 1.15.11
- Issued two schedules via the helm values, one with EBS snapshot and one without
```yaml
schedules:
  nightly:
    schedule: "17 2 * * *"
    template:
      ttl: "336h"
  nightly-exclude-snapshot:
    schedule: "27 2 * * *"
    template:
      snapshotVolumes: false
      ttl: "336h"
```
- Installation of the chart was green, but the `schedule` resources were missing
```
helm upgrade --install --namespace velero -f values.velero.yaml velero vmware-tanzu/velero

...

==> MISSING
KIND                                NAME
velero.io/v1, Resource=schedules    velero-nightly-exclude-snapshot
velero.io/v1, Resource=schedules    velero-nightly

```
- Confirmed missing `schedule` resources
```
kubectl get schedules.velero.io -A                                                                                                                                             
No resources found
```

**What did you expect to happen:**
`schedule` resources to be created.

**Anything else you would like to add:**
I downloaded the same version of the Velero Helm Chart and templated it with my values files, which generated the `schedule` manifests
```yaml
---
# Source: velero/templates/schedule.yaml

apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: release-name-velero-nightly
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: velero-2.12.17
spec:
  schedule: "17 2 * * *"
  template:
    ttl: 336h

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: release-name-velero-nightly-exclude-snapshot
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: velero-2.12.17
spec:
  schedule: "27 2 * * *"
  template:
    snapshotVolumes: false
    ttl: 336h

---
```
I then applied this manually against the cluster and got a success return
```bash
kubectl apply -f velero-schedule.yaml 
schedule.velero.io/release-name-velero-nightly created
schedule.velero.io/release-name-velero-nightly-exclude-snapshot created

kubectl get schedules.velero.io                                                                                                                                               
NAME                                           AGE
release-name-velero-nightly                    36s
release-name-velero-nightly-exclude-snapshot   36s
```

**Environment:**

- helm version (use `helm version`): 2.16.1
- helm chart version and app version: 
  - Chart - velero-2.12.17
  - App - 1.4.2
- Kubernetes version (use `kubectl version`): 1.15.11
- Cloud provider or hardware configuration: AWS EKS
