### ISSUE TITLE
Unable to add annotations for WLI 

### ISSUE THREAD

**Issue by xUnholy** [vmware-tanzu/helm-charts#161]
Error: `coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>`

Should this not be the following:

```
{{- if .Values.serviceAccount.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero.serverServiceAccount" . }}
{{- if .Values.serviceAccount.server.annotations }}
  annotations: 
{{ toYaml .Values.serviceAccount.server.annotations | nindent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
{{- end }}
```

As currently right now it's trying to add it to same line with `nindent` and it's failing.

https://github.com/vmware-tanzu/helm-charts/blob/a8ebcedb36a6f97b07219ab5963287865a86d209/charts/velero/templates/serviceaccount-server.yaml#L7

My `values.yaml` includes the following:

```
# Information about the Kubernetes service account Velero uses.
serviceAccount:
  server:
    create: true
    name:
    annotations:
      iam.gke.io/gcp-service-account: "[GSA_NAME]@[PROJECT_ID].iam.gserviceaccount.com"
```
