### ISSUE TITLE
Helm installation can't connect to DigitalOcean S3

### ISSUE THREAD

**Issue by ablts** [vmware-tanzu/helm-charts#191]
**What steps did you take and what happened:**
Can't connect to a DigitalOcean Space (S3) if velero is installed with helm chart. It works fine when installed with the velero CLI.

**What did you expect to happen:**
Velero connecting to the S3 even whether it's installed via the helm chart.

**The output of the following commands will help us better understand what's going on**:

If installed this way, everything is working 
```
velero install --provider velero.io/aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket my-bucket --backup-location-config s3Url=https://fra1.digitaloceanspaces.com,region=fra1 --use-volume-snapshots=false --secret-file ./velerocreds
```

But if I decide to use the helm chart, I got this error
```
msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:59" error.function=main.getSession logSource="pkg/controller/backup_sync_controller.go:168
```

I'm using this command to install the chart
```
helm install -f values.yml velero -n velero --version 2.14.1 vmware-tanzu/velero
```
with this values.yml flie
```
initContainers:
 - name: velero-plugin-for-aws 
   image: velero/velero-plugin-for-aws:v1.1.0
   imagePullPolicy: IfNotPresent
   volumeMounts:
     - mountPath: /target
       name: plugins
configuration:
  provider: velero.io/aws 
  backupStorageLocation:
    bucket: my-bucket
    config:
      region: fra1
      s3Url: https://fra1.digitaloceanspaces.com 
credentials:
  useSecret: true
  existingSecret: velero-creds
deployRestic: true
```

Of course, the secret is already created, and I checked directly in the pod to confirm that it is mounted in /credentials/cloud and that the file has the correct values (the exact same that the velerocreds file in the velero install command).

**Anything else you would like to add:**
I tried to compare the yaml of the components existing in the CLI install and in the helm install hoping to see some difference, but couldn't find anything.

**Environment:**

- helm version (use `helm version`): `v3.4.1`
- helm chart version and app version:
```
chart version: 2.14.1
app version: 1.5.2
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Digital Ocean`
