### ISSUE TITLE
BackupStorageLocation is created before CRD

### ISSUE THREAD

**Issue by vzabawski** [vmware-tanzu/helm-charts#220]
**What steps did you take and what happened:**
I'm using Velero with AWS plugin. Here's my values.yaml:

```
velero:
  enabled: true
  image:
    repository: velero/velero
    tag: 1.5.3

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  configuration:
  # Swift supports S3 API emulation, so use AWS provider
    provider: aws
    backupStorageLocation:
      provider: aws
      name: default
      bucket: jenkins-backups-prod
      config:
        region: eu-de-2
        s3ForcePathStyle: "true"
        s3Url: https://objectstore-3.example.com
        signatureVersion: "4"

    schedules:
      jenkins_backup:
        schedule: "0 0 * * *"
        template:
          ttl: "240h"
          includedNamespaces:
          - jenkins
    
  credentials:
    secretContents: {}
      # Speficied in secrets.yaml
      # cloud: |
      #   [default]
      #   aws_access_key_id=<REDACTED>
      #   aws_secret_access_key=<REDACTED>
```

**What did you expect to happen:**
Velero should be deployed, but instead, I receive the following error:

```
$ helm upgrade --install --atomic --timeout 5m jenkins . --namespace jenkins --values secrets.yaml --values values.yaml
Error: UPGRADE FAILED: release jenkins failed, and has been rolled back due to atomic being set: post-upgrade hooks failed: unable to build kubernetes object for deleting hook nft-jenkins/charts/velero/templates/backupstoragelocation.yaml: unable to recognize "": no matches for kind "BackupStorageLocation" in version "velero.io/v1"
```

**Environment:**

- helm version (use `helm version`): 
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

- helm chart version:
2.14.8

- K8s version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

I believe that happens because custom resource is being created before its CRD is actually installed. I'm currently working on modifying Velero Helm chart, so probably, I'll provide a pull request that fixes such issue.
