### ISSUE TITLE
Add ability to set default backupstoragelocation

### ISSUE THREAD

**Issue by sharkymcdongles** [vmware-tanzu/helm-charts#251]
**Describe the problem/challenge you have**
1.6.0 introduced a default setting to the crd:

https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/crds/backupstoragelocations.yaml#L26

They say to set this flag via velero cli, but this is not good practice if chart can do it for us by exposing this under the configuration.backupStorageLocation block.

**Describe the solution you'd like**
Add ability to set this to true or false.

**Comment by sharkymcdongles** [comment]
I found a workaround for now to those that are interested via an initContainer, but I am sure we can do this in a cleaner way:

```
initContainers:
- image: velero/velero:v1.6.0
  imagePullPolicy: IfNotPresent
  name: velero-set-bsl
  command: ['sh', '-c', '/velero backup-location set gcp --default']

```

**Comment by jenting** [comment]
You should be able to configure the BSL as the **default** like this

```yaml
configuration:
  provider: gcp
  backupStorageLocation:
    name: gcp
    provider: gcp
    bucket:
    prefix:
    default: true
```
