### ISSUE TITLE
Fail to install helm chart for bucket having numeric name

### ISSUE THREAD

**Issue by csgtree** [vmware-tanzu/helm-charts#275]
**What steps did you take and what happened:**
helm chart version is 2.16.0 and below is the values.yaml.
The bucket name is `12345`
```
configuration:
  logLevel: debug
  backupStorageLocation:
    bucket: "12345"
    caCert: xxxx
    config:
      insecureSkipTLSVerify: "true"
      region: "region1"
      s3ForcePathStyle: true
      s3Url: "https://oss-vcd.eng.vmware.com:55443/api/v1/s3"
    name: "bsl-aws"
    provider: "aws"
  provider: "aws"
  volumeSnapshotLocation:
    name: "vsl-vsphere"
    provider: "velero.io/vsphere"
credentials:
  name: "cloud-credentials"
  secretContents:
    cloud: "[default]\naws_access_key_id=abc\naws_secret_access_key=xyz"
  useSecret: true
image:
  repository: "velero/velero"
  tag: "v1.5.3"
initContainers:
- image: "velero/velero-plugin-for-aws:v1.1.0"
  imagePullPolicy: "IfNotPresent"
  name: "velero-plugin-for-aws"
  volumeMounts:
  - mountPath: "/target"
    name: "plugins"
- image: "vsphereveleroplugin/velero-plugin-for-vsphere:v1.1.1"
  imagePullPolicy: "IfNotPresent"
  name: "velero-plugin-for-vsphere"
  volumeMounts:
  - mountPath: "/target"
    name: "plugins"
serviceAccount:
  server:
    create: true
    name: "velero"

```

Here is the error I get if bucket name is `12345`. All works fine is bucket name has only letters like `foobar`
```
helm install velero ./ --namespace wangc -f values-ose.yaml
Error: failed post-install: warning: Hook post-install velero/templates/backupstoragelocation.yaml failed: BackupStorageLocation.velero.io "bsl-aws" is invalid: spec.objectStorage.bucket: Invalid value: "integer": spec.objectStorage.bucket in body must be of type string: "integer"
```

**What did you expect to happen:**
`12345` is valid bucket name for amazon s3, which should be supported by velero BackupStorageLocation as well

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 3.1.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
```
❯ helm list -n wangc
NAME  	NAMESPACE	REVISION	UPDATED                            	STATUS	CHART        	APP VERSION
velero	wangc    	1       	2021-06-21 21:12:52.93063 +0800 CST	failed	velero-2.16.0	1.5.3
```
- Kubernetes version (use `kubectl version`):
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.16) exceeds the supported minor version skew of +/-1
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
