### ISSUE TITLE
Upgrade CRDs does not work

### ISSUE THREAD

**Issue by ozlotusflare** [vmware-tanzu/helm-charts#279]
**What steps did you take and what happened:**
Hi everyone,
I have upgraded Velero helm chart from `2.15.0` to `2.22.0` and my upgrade failed with this error:

``` bash
Helm upgrade failed: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook velero/templates/backupstoragelocation.yaml: error validating "": error validating data: ValidationError(BackupStorageLocation.spec): unknown field "default" in io.velero.v1.BackupStorageLocation.spec
```
I suppose that the `upgradeCRDs: true` didn't start upgrade process and creation `BackupStorageLocation` ran early than `CRDs upgraade`
  

**What did you expect to happen:**
Smooth upgrade. 

**Anything else you would like to add:**
I think it will be better use `pre-install, pre-upgrade` hooks [here](https://github.com/vmware-tanzu/helm-charts/blob/2eeef6f73fa8a687ed5d424eeb842d552b17941d/charts/velero/templates/upgrade-crds.yaml#L8)

Because CRDs have to be installed before any other objects.

 P.s: Thank you for any help !
**Environment:**

- helm version (use `helm version`): v3.5.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-2.22.0	app version: 1.6.0
- Kubernetes version (use `kubectl version`): 1.20.4

**Comment by jenting** [comment]
@ozlotusflare,
Could you please provide your `values.yaml`?

**Comment by ozlotusflare** [comment]
Hi @jenting 
Sure:
``` yaml
...
values:
    configuration:
      provider: aws
      backupStorageLocation:
        name: aws
        bucket: "my_backup"
        prefix: "backups/k8s"
        default: true
        config:
          region: us-east-1
      volumeSnapshotLocation:
        name: aws-us-east-1
        provider: aws
        config:
          region: us-east-1
    schedules:
      volume-backup:
        schedule: "0 3 * * *"
        template:
          includedNamespaces:
            - '*'
          includedResources:
            - pv
            - pvc
          labelSelector:
            matchLabels:
              velero.io/volumesnapshot-create: "true"
          snapshotVolumes: true
          storageLocation: aws
          volumeSnapshotLocations:
            - aws-us-east-1
          ttl: "96h"
    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.20.4
      labels:
        app.kubernetes.io/name: velero-upgrade-crds
        io.kubernetes.pod.namespace: velero
    upgradeCRDs: true
    podAnnotations:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/fileset.stderr: "error"
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.1.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
...
```
