### ISSUE TITLE
[aws] config has invalid keys [serviceAccount]

### ISSUE THREAD

**Issue by withernet** [vmware-tanzu/helm-charts#286]
**What steps did you take and what happened:**
Installing via helm chart; used latest release and tried 2.22.0, same error.

**What did you expect to happen:**
No issues with regards to deploying velero

**The output of the following commands will help us better understand what's going on**:
```
time="2021-07-14T18:19:14Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = config has invalid keys [serviceAccount]; valid keys are [region s3Url publicUrl kmsKeyId s3ForcePathStyle signatureVersion credentialsFile profile serverSideEncryption insecureSkipTLSVerify bucket prefix caCert]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/controller/backup_sync_controller.go:175"
```

**Anything else you would like to add:**
Relevant values:
```
image:
  repository: velero/velero
  tag: v1.6.1
  pullPolicy: IfNotPresent

configuration:
  provider: aws
  logLevel: info
  objectStorage:
    bucket: bucket...
  backupStorageLocation:
    name: aws
    bucket: bucket
    config:
      region: region
      profile: default
  volumeSnapshotLocation:
    name: aws
    config:
      region: region
      profile: default

initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.2.0
  imagePullPolicy: IfNotPresent
  volumeMounts:
  - mountPath: /target
    name: plugins

serviceAccount:
  server:
    create: true
    name: service_account

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

podSecurityContext:
  fsGroup: 1337

metrics:
  enabled: true
  scrapeInterval: 60s
  scrapeTimeout: 10s

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    enabled: false

kubectl:
  image:
    repository: docker.io/bitnami/kubectl
    tag: 1.14.3

rbac:
  create: true
  clusterAdministrator: true

credentials:
  useSecret: false

backupsEnabled: true
snapshotsEnabled: true

```

**Environment:**

- helm version (use `helm version`): `v3.6.0`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): `velero    	default  	1       	2021-07-14 12:18:27.523532152 -0600 MDT  	deployed	velero-2.22.0   	1.6.0`
- Kubernetes version (use `kubectl version`): `v1.20.0`
- Kubernetes installer & version: 1.17
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): N/A
