### ISSUE TITLE
Custom secret name and key for extraEnvVars on DigitalOcean

### ISSUE THREAD

**Issue by qRoC** [vmware-tanzu/helm-charts#292]
**Describe the problem/challenge you have**

Hello.

>  variables such as "DIGITALOCEAN_TOKEN: \<your-key>".

What is `<your-key>`?

For configuration:

```yaml
credentials:
  existingSecret: velero-secrets
  extraEnvVars:
    DIGITALOCEAN_TOKEN: 'hello'
```

Need generate 2 secrets: `velero-secrets` and `velero`?

Because is generate:

```yaml
- name: DIGITALOCEAN_TOKEN
  valueFrom:
    secretKeyRef:
       name: velero
       key: DIGITALOCEAN_TOKEN
```

**Describe the solution you'd like**

Allow use custom secret name and secret key. Or just use `existingSecret` as secret name, and `value` as key in secret.

**Environment:**

- helm version (use `helm version`): v3.6.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-2.23.5, 1.6.2
- Kubernetes version (use `kubectl version`): v1.21.2
- Kubernetes installer & version: v1.21.2
- Cloud provider or hardware configuration: DigitalOcean
