### ISSUE TITLE
[Question] Schedules `includedNamespaces` - backup all namespaces without listing

### ISSUE THREAD

**Issue by mrszop** [vmware-tanzu/helm-charts#306]
Hello,

I'm kind of looking for a definition in the `values.yaml` for the scheduler part. I kind of have a lot of namespaces and there a new added an few deleted on a daily basis. Is there a way to say: "please backup all namespaces" without listing them specificly? Like my dummy code i.e.:

```yaml
schedules:
  dev:
    disabled: false
    labels:
      dev: foo
    annotations:
      dev: foo
    schedule: "*/30 * * * *"
    useOwnerReferencesInBackup: true
    template:
      ttl: "600h"
      includedNamespaces:
      - "*"
```

Cheers
