### ISSUE TITLE
config.provider as an requirement is confusing for new users and the deployment will fail

### ISSUE THREAD

**Issue by jensneuhaus** [vmware-tanzu/helm-charts#320]
**What steps did you take and what happened:**

Trying to deploy Velero without `config.provider` being set will not deploy anything. I expected that it still works with e.g. a config like the following, if one has two different providers: 

```
configuration:

    backupStorageLocation:
      provider: aws
       ... 

    volumeSnapshotLocation:
      provider: digitalocean.com/velero
```

**What did you expect to happen:**

Clear description in values.yaml file, that the `provider` is required; a check for it or a better handling if it is not existing.

**Anything else you would like to add:**

The deployment was not created because of [{{- if .Values.configuration.provider -}}](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L1) check; so I did not have any logs and it was hard to find out what actually is the problem.

**Environment:**

- helm version (use `helm version`): 3.7.1
- helm chart version and app version: 2.26.1
- Kubernetes version (use `kubectl version`): Server 1.21.5 (on Server)
- Cloud provider or hardware configuration: Digital ocean
