### ISSUE TITLE
Helm Templates Command for Velero - Encountered 3 issues

### ISSUE THREAD

**Issue by jailigao** [vmware-tanzu/helm-charts#331]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Im using helm templates and it seems that the helm chart is outdated. getting this error after running the yamls from the templates.

```
helm template velero vmware-tanzu/velero --namespace velero \
--output-dir $VELERO_FOLDER \
--set configuration.provider=azure \
--set-file credentials.secretContents.cloud=$TEMPLATE_ROOT/velero/credentials-velero \
--set configuration.backupStorageLocation.name='azure' \
--set configuration.backupStorageLocation.config.storageAccountKeyEnvVar='AZURE_STORAGE_ACCOUNT_ACCESS_KEY' \
--set configuration.backupStorageLocation.config.resourceGroup='unit-testing' \
--set configuration.backupStorageLocation.config.storageAccount='velerotst' \
--set configuration.backupStorageLocation.bucket='mycluster' \
--set configuration.volumeSnapshotLocation.name='azure' \
--set image.repository='velero/velero' \
--set image.pullPolicy=Always \
--set initContainers[0].name='velero-plugin-for-microsoft-azure' \
--set initContainers[0].image='velero/velero-plugin-for-microsoft-azure:master' \
--set initContainers[0].volumeMounts[0].mountPath='/target' \
--set initContainers[0].volumeMounts[0].name='plugins' 
kubectl create secret generic cloud-credentials --namespace velero --from-file cloud=credentials-velero ``

```

**What did you expect to happen:**
to run velero without getting error

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```
unable to recognize "backupstoragelocation.yaml": no matches for kind "BackupStorageLocation" in version "apiextensions.k8s.io/v1"
unable to recognize "volumesnapshotlocation.yaml": no matches for kind "VolumeSnapshotLocation" in version "apiextensions.k8s.io/v1"
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
**- adding this error as well, above error was encountered after several installation but below was the main issue I encountered **

Upon running the script the generated file with go to the template folder. Velero yaml were installed via kustomize and after running the command velero backup no logs where found.

`kubectl logs deployment/velero -n velero`

Error encountered:
Already applied all the recommended in github discussion and troubleshooting but no luck on my end.

Scenarios that ive tried to resolved the below error:

There is no existing backup storage location set as default - manually update the template for backupstoragelocation.yaml. updated the namespace and name to default. Then will get another error AZURE_CREDENTIALS_FILE no such file.
Im using LENS5 application and after checking the Secrets tab - no /credentials/cloud file in there. I assume that this file is located here as per the velero documentation.

```
time="2021-12-28T11:01:04Z" level=warning msg="There is no existing backup storage location set as default. Please see `velero backup-location -h` for options." controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:173"
time="2021-12-28T11:01:14Z" level=error msg="Error getting a backup store" backup-storage-location=azure controller=backup-storage-location error="rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/common.go:42" error.function=main.loadEnv logSource="pkg/controller/backup_storage_location_controller.go:100"
time="2021-12-28T11:01:14Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/0/1)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:166"
time="2021-12-28T11:01:14Z" level=warning msg="There is no existing backup storage location set as default. Please see `velero backup-location -h` for options." controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:173"
```
**Environment:**

- helm version (use `helm version`): 3.7.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 2.27.1
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
- Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- 
- Kubernetes installer & version:
- Cloud provider or hardware configuration: azure
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
@jailigao,
I think it's because the `helm template` by default won't render the CRD manifests.
Please try run `helm template` with flag `--include-crds`, thank you.

**Comment by jailigao** [comment]
Forgot to update. Already resolved the issue. How about with my other concern? That's my issue now

**Comment by jenting** [comment]
> Forgot to update. Already resolved the issue. How about with my other concern? That's my issue now

Could you please describe what's the rest concerns?

**Comment by jailigao** [comment]
``
time="2022-01-03T15:28:58Z" level=error msg="Error getting backup store for this location" backupLocation=azure controller=backup-sync error="rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/common.go:42" error.function=main.loadEnv logSource="pkg/controller/backup_sync_controller.go:175"

Here's my current issue. Already applied all the resolution found in github and other resources but no luck

**Comment by jailigao** [comment]
Any updates on this?

**Comment by jenting** [comment]
> Any updates on this?

Could you please check the rendered template includes the `AZURE_CREDENTIALS_FILE` as `/credentials/cloud`?
https://github.com/vmware-tanzu/helm-charts/blob/ae05805/charts/velero/templates/deployment.yaml#L162-L163

**Comment by jailigao** [comment]
Yes, here's my deployment yaml:
```
....
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: cloud-credentials
              mountPath: /credentials
            - name: scratch
              mountPath: /scratch
          env:
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LD_LIBRARY_PATH
              value: /plugins
            - name: AZURE_CREDENTIALS_FILE
              value: /credentials/cloud
      dnsPolicy: ClusterFirst
      initContainers:
        - image: velero/velero-plugin-for-microsoft-azure:master
          name: velero-plugin-for-microsoft-azure
          volumeMounts:
          - mountPath: /target
            name: plugins
      volumes:
        - name: cloud-credentials
          secret:
            secretName: velero``
```
