### ISSUE TITLE
Unable to backup workload to s3 target with restic

### ISSUE THREAD

**Issue by barryboubakar** [vmware-tanzu/helm-charts#332]
**What steps did you take and what happened:**
I created my helm `values.yaml` file. 

```
#--------------------------------------------------#
# Backup Storage Location Configuration Parameters #
#--------------------------------------------------#
configuration:
  provider: aws
  defaultVolumesToRestic: true
  backupStorageLocation:
    name: mybackupstoragelocationname
    bucket: mybucketname
    config:
      region: eu-west-3
      s3Url: "https://storagegrid-s3.example.com"
      s3ForcePathStyle: true
    default: true      
    caCert: "BASE64 ENCODED CERT VALUE IN ONE LINE"  

credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=MY_S3_ACCESS_KEY
      aws_secret_access_key=MY_S3_SECRET_KEY
      output=json

#-------------------------------------------#
# Velero General Configuration Parameters #
#-------------------------------------------#
image:
  tag: v1.7.0

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.3.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configMaps:
  restic-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/restic: RestoreItemAction
    data:
      image: velero/velero-restic-restore-helper:v1.7.0

kubectl:
  image:
    repository: bitnami/kubectl

snapshotsEnabled: false
deployRestic: true
```
Then I install velero with the following command:

`helm install velero vmware-tanzu/velero --version 2.26.1 --namespace velero --create-namespace -f values.yaml`

**What did you expect to happen:**
I have 2 clusters. On both clusters velero is successfully installed. However backups works on the first clusters but not on the second one. 

I would like the manual and scheduled backups to work on the second cluster also.

**The output of the following commands will help us better understand what's going on**:
I get this kind of error when I run the velero backup command:

```
time="2021-11-29T08:00:39Z" level=error msg="Error checking repository for stale locks" controller=restic-repo error="error running command=restic unlock --repo=s3:https://storagegrid-s3.example.com/3p-velero/restic/3p --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cacert=/tmp/cacert-bsl-uro-3p914046061 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open config file: Stat: The specified key does not exist.\nIs there a repository at the following location?\ns3:https://storagegrid-s3.example.com/3p-velero/restic/3p\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:276" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:144" name=3p-bsl-uro-3p-72h2g namespace=velero
time="2021-11-29T08:00:39Z" level=error msg="Error checking repository for stale locks" controller=restic-repo error="error running command=restic unlock --repo=s3:https://storagegrid-s3.example.com/3p-velero/restic/cattle-prometheus --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cacert=/tmp/cacert-bsl-uro-3p692689128 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open config file: Stat: The specified key does not exist.\nIs there a repository at the following location?\ns3:https://storagegrid-s3.example.com/3p-velero/restic/cattle-prometheus\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:276" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:144" name=cattle-prometheus-bsl-uro-3p-rqqsm namespace=velero
time="2021-11-29T08:00:39Z" level=error msg="Error checking repository for stale locks" controller=restic-repo error="error running command=restic unlock --repo=s3:https://storagegrid-s3.example.com/3p-velero/restic/velero --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cacert=/tmp/cacert-bsl-uro-3p737709863 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open config file: Stat: The specified key does not exist.\nIs there a repository at the following location?\ns3:https://storagegrid-s3.example.com/3p-velero/restic/velero\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:276" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:144" name=velero-bsl-uro-3p-zxtvt namespace=velero
```

**Environment:**

- helm version (use `helm version`):  v3.4.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 2.26.1
- Kubernetes version (use `kubectl version`): v1.18.10
- Kubernetes installer & version: RKE 1.2.3 and Rancher 2.4.11
- Cloud provider or hardware configuration: vSphere 6.7 u3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
- S3 provider: NetApp StorageGrid 11.4
