### ISSUE TITLE
Using GCP workload identity

### ISSUE THREAD

**Issue by mrszop** [vmware-tanzu/helm-charts#351]
Hey folks,

I'm having a hard time to define Velero in combination with GCP workload identity. I tried to follow [this guide](https://github.com/vmware-tanzu/velero-plugin-for-gcp#option-2-using-workload-identity), but I'm using helm chart via helmfile and therefor need to adapt it. My work so far.

values.yaml

```yaml
---
credentials:
  useSecret: false

deployRestic: true

configuration:
  defaultVolumesToRestic: true
  provider: gcp
  backupStorageLocation:
    bucket: "3ma2-eu-..."
    config:
      serviceAccount: "velero@szop-prod.iam.gserviceaccount.com"
serviceAccount:
    name: "velero"
    annotations:
      iam.gke.io/gcp-service-account: "velero@szop-prod.iam.gserviceaccount.com"
```

I'm always getting:

```console
level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = googleapi: Error 403: Caller does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden" error.file="/go/src/velero-plugin-for-gcp/velero-plugin-for-gcp/object_store.go:216" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:182"
```

Roles assigned are, which I've got [from this link.](https://github.com/vmware-tanzu/velero-plugin-for-gcp#create-custom-role-with-permissions-for-the-velero-gsa). I've called them velero.backup not velero.server.

```
ROLE
projects/szop-prod/roles/velero.backup
roles/storage.admin
```

Hope you can help me out.

Cheers,
Szop

**Comment by jenting** [comment]
The related issue I could find is #242. However, you did configure the `credentials.useSecret=false` already but it's not working in your environment :thinking: .

**Comment by mrszop** [comment]
Ok,

I've got it up and running:

```yaml
---
initContainers:
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.4.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  serviceMonitor:
    enabled: true

configuration:
  defaultVolumesToRestic: true

deployRestic: true

configuration:
  provider: gcp
  backupStorageLocation:
    name: "default"
    bucket: "BUCKET-NAME"
    config:
      serviceAccount: "velero-adv-inc-lw-dev-1@PROJECT-ID.iam.gserviceaccount.com"

serviceAccount:
  server:
    create: false
    name: "velero-adv-inc-lw-dev-1"
    annotations:
      iam.gke.io/gcp-service-account: "velero-adv-inc-lw-dev-1@PROJECT-ID.iam.gserviceaccount.com"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

restic:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

credentials:
  useSecret: false

schedules:
  velero:
    disabled: false
    labels:
      velero: velero
    annotations:
      velero: velero
    schedule: "30 6 * * *"
    useOwnerReferencesInBackup: true
    template:
      ttl: "120h"
      includedNamespaces:
      - velero
```

Definition of GCP SA and GKE SA like here: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

If someone need's help with this, let me know.

**Comment by jenting** [comment]
@mrszop 
Would you mind helping us update the `values.yaml` to improve the document if the users use GCP workload identity?
Thank you.

**Comment by mrszop** [comment]
Sure. Shall I create a new values.yaml for workload identities only? What's your idea of implementing this?

**Comment by jenting** [comment]
Would it possible to adding some comment/sentence/wording to the existing values.yaml?

**Comment by red8888** [comment]
There is already a doc for this: https://github.com/vmware-tanzu/velero-plugin-for-gcp?tab=readme-ov-file#option-3-using-gke-workload-identity.

Its been kind of a pain figuring out what a basic, correct GCP config is with the chart. It would be nice if there was just a minimal, working snippet for the chart for different providers (like there is for the cli). I had to look online to find the right initContainers config- maybe thats documented somewhere?

All we need is a minimum viable example helm snippet for the docs. Essentially just translating the cli config in the wiki I linked to, to a succinct, known working helm snippet. Like this? (excluding the initContainers which should be added to it as well)

```
configuration:
  provider: gcp
  backupStorageLocation:
    name: "default"
    bucket: "BUCKET-NAME"
    config:
      serviceAccount: "velero-adv-inc-lw-dev-1@PROJECT-ID.iam.gserviceaccount.com"

serviceAccount:
  server:
    name: "velero-adv-inc-lw-dev-1"
    annotations:
      iam.gke.io/gcp-service-account: "velero-adv-inc-lw-dev-1@PROJECT-ID.iam.gserviceaccount.com"

credentials:
  useSecret: false
```
