### ISSUE TITLE
Updating CRD's not working failed to upgrade with helm 

### ISSUE THREAD

**Issue by ujwala02** [vmware-tanzu/helm-charts#352]
$ helm list --failed -n velero
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
velero  velero          2               2022-03-03 23:30:10.7192487 +0530 IST   failed  velero-2.28.0   1.8.0

$ helm upgrade velero vmware-tanzu/velero --namespace velero --reuse-values
Error: UPGRADE FAILED: post-upgrade hooks failed: job failed: BackoffLimitExceeded

we are using helm version 3

**Comment by jenting** [comment]
It seems like pulling the kubectl image can succeed, probably hit the docket hub rate limit.

**Comment by mshivanna** [comment]
In our case the upgrade job fails with this error `The CustomResourceDefinition "restores.velero.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
customresourcedefinition.apiextensions.k8s.io/volumesnapshotlocations.velero.io unchanged`

**Comment by jenting** [comment]
> In our case the upgrade job fails with this error `The CustomResourceDefinition "restores.velero.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema customresourcedefinition.apiextensions.k8s.io/volumesnapshotlocations.velero.io unchanged`

Which Kubernetes version you are running?

**Comment by mshivanna** [comment]
1.18

**Comment by jenting** [comment]
> 1.18

And which chart version?

**Comment by mshivanna** [comment]
2.29.3

**Comment by robertchen** [comment]
I got same issue, the upgrade crds pod has this error:

$ k-n util logs  velero-upgrade-crds-9b654
Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout

**Comment by mshivanna** [comment]
1.18

**Comment by tobiasehlert** [comment]
I encounter the same issue on my 1.19 EKS cluster. :(

Noticed also following error in the initcontainer:
```plain
exec /bin/sh: exec format error
```

Followed following installation process:
https://aws.amazon.com/blogs/containers/backup-and-restore-your-amazon-eks-cluster-resources-using-velero/

Here is my values.yaml:
```yaml
configuration:
  backupStorageLocation:
    - bucket: my-velero-backup-on-s3
  volumeSnapshotLocation:
    - config:
        region: eu-north-1
credentials:
  useSecret: false
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.7.0
    volumeMounts:
      - mountPath: /target
        name: plugins
serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::awsaccountid:role/velero-backup"
```
