### ISSUE TITLE
GCP/GKE: velero backup logs error 403

### ISSUE THREAD

**Issue by mrszop** [vmware-tanzu/helm-charts#357]
**What steps did you take and what happened:**

Im running a scheduled backup every morning at 6:30 defined like this:

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade,post-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    velero: velero
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.29.0
    velero: velero
  name: velero-velero
  namespace: velero
spec:
  schedule: 30 6 * * *
  template:
    includedNamespaces:
    - velero
    ttl: 120h
  useOwnerReferencesInBackup: true
```

If I want to take a look into the backup for details, with local velero CLI, because it partially failed i.e., I'm not allowed according to Velero Pod Log:

```sh
velero backup logs velero-20220323120927
```

**What did you expect to happen:**
Get details about backup

**The output of the following commands will help us better understand what's going on**:

```sh
time="2022-03-23T12:26:48Z" level=error msg="Reconciler error" error="rpc error: code = Unknown desc = googleapi: Error 403: The caller does not have permission, forbidden" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:153" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=velero-adv-inc-cloud-advancer-staging-20220323120927-13291770-b7d2-4723-8fe4-9e1ec9c889e5 namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
```

**Anything else you would like to add:**

I'm using GCP workload identities which works fine according to my GCP bucket and Velero Pod logs.

**Environment:**

- helm version (use `helm version`): `version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):

```sh
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
velero  velero          3               2022-03-23 13:03:20.698368 +0100 CET    deployed        velero-2.29.0   1.8.0
```

- Kubernetes version (use `kubectl version`):

```sh
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9-gke.1002", GitCommit:"f87f9d952767b966e72a4bd75afea25dea187bbf", GitTreeState:"clean", BuildDate:"2022-02-25T18:12:32Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):

```sh
NAME                                           STATUS   ROLES    AGE     VERSION            INTERNAL-IP    EXTERNAL-IP      OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gke-default-pool-f463d8dc-0knj   Ready    <none>   4d23h   v1.21.9-gke.1002   10.156.0.100   ---    Container-Optimized OS from Google   5.4.170+         docker://20.10.3
```

Installed via Helm Chart / Helmfile like this: https://github.com/vmware-tanzu/helm-charts/issues/351

Cheers,
Szop
