### ISSUE TITLE
exclude certain resources from the backup schedule

### ISSUE THREAD

**Issue by dmitry-mightydevops** [vmware-tanzu/helm-charts#378]
I need to exclude certain resource types from the backup schedule

specifically I need this:
```
--exclude-resources=orders.acme.cert-manager.io,challenges.acme.cert-manager.io,certificaterequests.cert-manager.io
```

this is my schedule:

```yaml
staging:
  labels:
    backup: staging
  schedule: "@every 24h"
  template:
    ttl: "480h"
    includedNamespaces:
    - staging
```

what should be the key/value to achieve this?

will the following work?

```yaml
staging:
  labels:
    backup: staging
  schedule: "@every 24h"
  template:
    ttl: "480h"
    includedNamespaces:
    - staging
    excludeResources:
    - orders.acme.cert-manager.io
    - challenges.acme.cert-manager.io
    - certificaterequests.cert-manager.io
```

os excludedResources? Or excludeResources: "long string" vs array.
