### ISSUE TITLE
Velero schedules specified in values are not removed from server after removal

### ISSUE THREAD

**Issue by jprecuch** [vmware-tanzu/helm-charts#392]
**What steps did you take and what happened:**
We specified schedules using values.yaml file:
```
schedules:
  full-24h-all-ns-bkp:
    schedule: "30 8 * * *"
    template:
      ttl: "336h0m0s"
      includedNamespaces:
        - '*'
      snapshotVolumes: true
  full-12h-all-ns-novols-bkp:
    schedule: "15 */12 * * *"
    template:
      ttl: "168h0m0s"
      includedNamespaces:
        - '*'
      snapshotVolumes: false
  mysql-hourly-all-ns-bkp:
    schedule: "0 * * * *"
    template:
      ttl: "72h0m0s"
      includedNamespaces:
        - '*'
      labelSelector:
        matchLabels:
          app: mysql
      snapshotVolumes: true
```
This leads to:
```
$ velero schedule get
NAME                                STATUS    CREATED                         SCHEDULE        BACKUP TTL   LAST BACKUP   SELECTOR
velero-full-12h-all-ns-novols-bkp   Enabled   2022-08-16 11:36:04 +0000 UTC   15 */12 * * *   168h0m0s     n/a           <none>
velero-full-24h-all-ns-bkp          Enabled   2022-08-16 11:36:04 +0000 UTC   30 8 * * *      336h0m0s     n/a           <none>
velero-mysql-hourly-all-ns-bkp      Enabled   2022-08-16 11:36:04 +0000 UTC   0 * * * *       72h0m0s      5m ago        app=mysql
```
However if we remove one of these schedules from values.yaml and then reupgrade, they are not removed and the schedules are still active on the region which had previous values

**What did you expect to happen:**
If we remove one schedule from list of schedules in values.yaml, it will be also deleted (after next upgrade) from the server side as well.

**Environment:**

- helm version (use `helm version`): v3.9.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
```
NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
velero	velero   	1       	2022-08-16 11:35:45.905097751 +0000 UTC	deployed	velero-2.31.0	1.9.0
```
- Kubernetes version (use `kubectl version`): v1.24.2-gke.1900
- Kubernetes installer & version: v1.24.2-gke.1900
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): containerd
