### ISSUE TITLE
credentials.existingSecret not honored (Secret exists and cannot be imported into the current release)

### ISSUE THREAD

**Issue by diegonuevo** [vmware-tanzu/helm-charts#406]
Hi, I'm trying to install the helm chart in an AKS cluster with the [Velero plugin for Azure](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure). I'm using a custom values.yaml file and specifying a pre-existing secret to authenticate:
```
initContainers:
 - name: velero-plugin-for-microsoft-azure
   image: velero/velero-plugin-for-microsoft-azure:v1.5.1
   imagePullPolicy: IfNotPresent
   volumeMounts:
     - mountPath: /target
       name: plugins
configuration:
  provider: azure
  backupStorageLocation:
    bucket: velero-backup-bucket
    config:
      resourceGroup: backup-rg
      storageAccount: redacted-storage-account
  volumeSnapshotLocation:
    config:
      resourceGroup: backup-rg
  credentials:
    useSecret: true
    existingSecret: velero-backup
```
This is my existing secret (redacted, for obvious reasons):
```
apiVersion: v1
data:
  cloud: <credentials file encoded in base64>
kind: Secret
metadata:
  name: velero-backup
  namespace: backup
type: Opaque
```

With this command, I expect the helm chart not to deploy a new secret, but use the one specified, which already exists, but I'm getting this error:
```
$ helm install velero-backup vmware-tanzu/velero --version 2.31.6 --namespace backup -f values.yaml
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "velero-backup" in namespace "backup" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "velero-backup"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "backup"
```

I re-created the secret, adding the annotations and the label as suggested by the error message:
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: velero-backup
    meta.helm.sh/release-namespace: backup
  labels:
    app.kubernetes.io/managed-by: Helm
  name: velero-backup
  namespace: backup
data:
  cloud: <credentials file encoded in base64>
type: Opaque
```
With these changes in place, the installation goes fine:
```
$ helm install velero-backup vmware-tanzu/velero --version 2.31.6 --namespace backup -f values.yaml
NAME: velero-backup
LAST DEPLOYED: Thu Oct  6 15:57:17 2022
NAMESPACE: backup
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Check that the velero is up and running:

    kubectl get deployment/velero-backup -n backup

Check that the secret has been created:

    kubectl get secret/velero-backup -n backup

Once velero server is up and running you need the client before you can use it
1. wget https://github.com/vmware-tanzu/velero/releases/download/v1.9.1/velero-v1.9.1-darwin-amd64.tar.gz
2. tar -xvf velero-v1.9.1-darwin-amd64.tar.gz -C velero-client

More info on the official site: https://velero.io/docs
```

But I noticed that the secret is updated by helm and the data property is gone (and so are the credentials):
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: velero-backup
    meta.helm.sh/release-namespace: backup
  labels:
    app.kubernetes.io/instance: velero-backup
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.31.6
  name: velero-backup
  namespace: backup
type: Opaque
```
Notice there is no data property any more!

As expected, the velero server fails to authenticate and store anything on the storage account.

Am I missing anything? I've read multiple times the available properties in the sample values.yaml file, and I can't find anything that may help in this case.

**Environment:**

- helm version: v3.9.4
- helm chart version: 2.31.6
- helm app version (velero): 1.9.1 
- velero-plugin-for-microsoft-azure version: v1.5.1
- kubectl version: v1.23.10
- Kubernetes cluster (server) version: v1.22.6
- Cloud provider: Azure AKS and storage account for storing backups
