### ISSUE TITLE
useOwnerReferencesInBackup not respected

### ISSUE THREAD

**Issue by cam3ron2** [vmware-tanzu/helm-charts#416]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Despite setting `schedules.mybackup.useOwnerReferencesInBackup` to false the resulting schedule generated by helm is missing the `useOwnerReferencesInBackup` option. 

given the following values.yaml (taken directly from the example in values.yaml in this repo):

```yaml
schedules:
  mybackup:
    disabled: false
    labels:
      myenv: foo
    annotations:
      myenv: foo
    schedule: "0 0 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "240h"
      includedNamespaces:
      - foo
```

running `helm template velero tanzu/velero -f values.yaml` results in the following schedule:

```yaml
# Source: velero/templates/schedule.yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-mybackup
  namespace: argocd
  annotations:
    myenv: foo
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-2.32.1
    myenv: foo
spec:
  schedule: "0 0 * * *"
  template:
    includedNamespaces:
    - foo
    ttl: 240h
```

As you can see, `useOwnerReferencesInBackup` was not passed correctly into the schedule template.

**What did you expect to happen:**

`useOwnerReferencesInBackup` should be passed into the template and be present in the resulting manifest.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`):  v3.10.1
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 2.32.1, 1.9.2
- Kubernetes version (use `kubectl version`): 1.24.6
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):  OSX
