### ISSUE TITLE
"uploaderType: kopia"  / pod shows "--uploader-type=restic"

### ISSUE THREAD

**Issue by reefland** [vmware-tanzu/helm-charts#432]
**What steps did you take and what happened:**

I defined in my values.yaml:

```
uploaderType: kopia
```

The Deployment/Pod has `--uploader-type=restic`

**What did you expect to happen:**

I expected the pod to have `upploader-type` set to `kopia` not `restic`.  I can't find much documented on this, but I saw references to kopia support being included in v1.10 and this seems to be the way to set it.  v1.10 is my initial installation, this is not an upgraded install.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The restic backup is working fine, just not what I configured.

**Environment:**

- helm version (use `helm version`): 
```
$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
Applied via ArgoCD:
```
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 3.1.0
```
- Kubernetes version (use `kubectl version`):
```
$ sudo kubectl version --short
Client Version: v1.25.4+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.4+k3s1
```
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1

**Comment by jenting** [comment]
@qiuming-best could you help with this issue when you are free?

**Comment by orangewolf** [comment]
just a drive by as I found this ticket while looking for docs on kopia setup. It looks like you need:
```yaml
configuration:
  uploaderType: kopia
```
  
if you add the heading does it then give you the correct type?

**Comment by reefland** [comment]
@orangewolf - sorry if it wasn't clear, but that is exactly what I have.

**Comment by qiuming-best** [comment]
@reefland I think you encountered the same issue https://github.com/vmware-tanzu/velero/issues/5782

**Comment by qiuming-best** [comment]
@orangewolf For the deployment of velero, [here](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L83) is the configuration of uploader type, and v3.0.0 brought this change 

Your installation is Applied via ArgoCD, I'm not sure how your ArgoCD renders the `deployment.yaml` file.

**Comment by reefland** [comment]
@qiuming-best - thanks for the response. 

This is a snip of what is rendered:
```
....
        credentials:
          useSecret: true
          existingSecret: velero-secrets-store

        deployNodeAgent: true
        uploaderType: kopia
        defaultVolumesToFsBackup: true

        schedules:
....
```

Credentials are working fine, DaemonSet is deployed, its doing File System backups and schedules are working great. Don't see a reason why `uploaderType: kopia` would have been handled differently. 

In any case, restic has been working fine.  I'll remove the `uploaderType: kopia` is stick with the default.

**Comment by qiuming-best** [comment]
@reefland I noticed the snippet you pasted:

uploaderType has the same level with credentials, which is not correct, and it should be like this:

```
        credentials:
          useSecret: true
          existingSecret: velero-secrets-store
        configuration:
          uploaderType: kopia
```

**Comment by reefland** [comment]
As much as I want to blame a bad cut & paste, I'll blame blurry eyes with `vi`. I sweat I quadruple checked it. 

I'm going to delete the namespace and install Velero again to confirm it switches to `kopia` as it seems to have performance / space advantages over `restic` and I saw some comments that `kopia` is likely the future direction for Velero.  So might as well fix it now.

**Comment by orangewolf** [comment]
just confirming here - I deployed a brand new one today via helm chart. When you get the yaml structure correct it does use kopia instead of restic correctly.

**Comment by reefland** [comment]
I agree... you get the YAML right, and it works :)

Seeing this in ArgoCD now:

```
spec:
  containers:
    - args:
        - server
        - '--uploader-type=kopia'
        - '--default-volumes-to-fs-backup'
        - '--features=EnableCSI'
```

I'll let all the backups schedules run overnight to confirm all it is well.
