### ISSUE TITLE
Schedules Not Deploying / ArgoCD

### ISSUE THREAD

**Issue by reefland** [vmware-tanzu/helm-charts#433]
**What steps did you take and what happened:**
Deployed helm chart using ArgoCD / Helm.  Updated deployment to include a schedule in the values.yaml:

```
        schedules:
          gitea:
            disabled: false
            schedule: "0 5 * * *"
            # Help prevent ArgoCD from deleting backups on upgrades:
            # https://adamrushuk.github.io/how-to-avoid-backup-deletion-during-velero-upgrades-via-argo-cd/
            useOwnerReferencesInBackup: true
            template:
              ttl: "240h"
              includedNamespaces:
                - gitea
              includedResources:
                - snapshot.storage.k8s.io/v1/VolumeSnapshot
                - snapshot.storage.k8s.io/v1/VolumeSnapshotClass
                - snapshot.storage.k8s.io/v1/VolumeSnapshotContent
                - v1/PersistentVolume
                - v1/PersistentVolumeClaim
              storageLocation: minio
              volumeSnapshotLocations: minio
              # Perform filesystem backup to storage
              defaultVolumesToFsBackup: true
```

**What did you expect to happen:**

I expected the Schedule to be created upon ArgoCD application sync:
```
$ velero schedule get

# nothing here
```

**Anything else you would like to add:**

Perhaps this is related to #388 where ServiceMonitor is not deploying under ArgoCD either??

**Environment:**

- helm version (use `helm version`): 
```
$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
Applied via ArgoCD:
```
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 3.1.0
```
- Kubernetes version (use `kubectl version`):
```
$ sudo kubectl version --short
Client Version: v1.25.4+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.4+k3s1
```
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1
