### ISSUE TITLE
Velero: configMaps

### ISSUE THREAD

**Issue by iusergii** [vmware-tanzu/helm-charts#445]
I want to add [Changing PV/PVC Storage Classes](https://velero.io/docs/main/restore-reference/#changing-pvpvc-storage-classes) via helm chart by including the following config:

```yaml
configMaps:
  change-storage-class-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/change-storage-class: RestoreItemAction
    data:
      default: my-default
```
Template rendering fails with error:
```
Error: template: velero/charts/velero/templates/NOTES.txt:58:53: executing "velero/charts/velero/templates/NOTES.txt" at <$value.data.image>: wrong type for value; expected string; got interface {}
helm.go:84: [debug] template: velero/charts/velero/templates/NOTES.txt:58:53: executing "velero/charts/velero/templates/NOTES.txt" at <$value.data.image>: wrong type for value; expected string; got interface {}
```

**Environment:**
- helm chart version and app version: 3.1.4
