### ISSUE TITLE
Excluding snapshots does not work in Velero Helm Chart

### ISSUE THREAD

**Issue by rdvansloten** [vmware-tanzu/helm-charts#466]
**What steps did you take and what happened:**
I executed this schedule:

```
schedules:
  test:
    disabled: false
    labels: {}
    annotations: {}
    schedule: "0 8 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "240h"
      storageLocation: default
      includedNamespaces:
        - '*'
      includedResources:
        - '*'
```

and set these options:
```
snapshotsEnabled: false
```

```
volumeSnapshotLocation: []
```

Logs (120x)
```
time="2023-06-13T08:00:50Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/velero-test-20230613080036 error="rpc error: code = Unknown desc = config has invalid keys [storageAccount]; valid keys are [resourceGroup apiTimeout subscriptionId incremental]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.6.2/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:524" name=pvc-REDACTED namespace= persistentVolume=pvc-REDACTED resource=persistentvolumes volumeSnapshotLocation=default
```

This does not occur when I run `velero backup create my-backup --include-namespaces '*' --snapshot-volumes=false` manually:

```
NAME                         STATUS            ERRORS   WARNINGS   
my-backup                    Completed         0        0          
test-backup-fixed-values-3   Completed         0        0 
test-backup-fixed-values-4   Completed         0        0 
velero-test-20230613092059   PartiallyFailed   124      0  
```

**What did you expect to happen:**
That my backup does not try to capture snapshots.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): v3.12.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):  velero-4.0.3
- Kubernetes version (use `kubectl version`): 1.24
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
