### ISSUE TITLE
BackupStorageLocation does not support IAM Authentication

### ISSUE THREAD

**Issue by cdestefano-777** [vmware-tanzu/helm-charts#476]
**What steps did you take and what happened:**
We are implementing velero in lower environments using helm charts. On the upgrade / install of veler using the following command, the CRD for backupstoragelocation was unavailable due to no support on IAM role authentication: 

```
helm upgrade velero vmware-tanzu/velero \
    --install \
    --namespace ops \
    --version 4.1.0 \
    --values velero/values.yaml \
    --values velero/dev/values.yaml
```

Where `values.yaml`: 
```
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.7.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  enabled: false

credentials:
  useSecret: false
```

and `dev/values.yaml`:
```
podAnnotations:
  iam.amazonaws.com/role: "REDACTED"

configuration:
  backupStorageLocation:
    - name: velero
      bucket: "REDACTED"
      provider: aws
      config:
        region: us-east-1
  volumeSnapshotLocation:
    - name: velero
      provider: aws
      config:
        region: us-east-1

# https://github.com/vmware-tanzu/velero/blob/master/site/docs/master/api-types/schedule.md
schedules:
  dev-backup:
    disabled: false
    schedule: "0 * * * *"
    template:
      ttl: "72h"
      storageLocation: default
      includedNamespaces:
        - dev
      excludedResources:
        - cronjobs.batch
        - jobs.batch
  dev-backup-batch:
    disabled: false
    schedule: "0 * * * *"
    template:
      ttl: "72h"
      storageLocation: default
      includedNamespaces:
        - dev
      includedResources:
        - cronjobs.batch
        - jobs.batch
```

The BackupStorageLocation CRD is not available due to the fact that we are not assigning credentials anywhere in the BackupStorageLocation resource and throw the following error message: ```BackupStorageLocation "velero" is unavailable: rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.  │
│                          For verbose messaging see aws.Config.CredentialsChainVerboseErrors``` . Documentation provides how to pass in Secret and Access Keys for a AWS User (https://velero.io/docs/v1.6/troubleshooting/#is-velero-using-the-correct-cloud-credentials), however, we would prefer to use IAM roles and policies in order to authenticate, as this is supported on pods using pod annotations with the ARN of the IAM role. Template only supports `credentials`: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/backupstoragelocation.yaml

**What did you expect to happen:**
BackupStorageLocation receives an IAM role in the charts on the following template https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/backupstoragelocation.yaml and becomes available.

**The output of the following commands will help us better understand what's going on**:
```BackupStorageLocation "velero" is unavailable: rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.  │
│                          For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
