### ISSUE TITLE
Multiple role annotation in velero service account

### ISSUE THREAD

**Issue by prasoon-pxc** [vmware-tanzu/helm-charts#507]
**Describe the problem/challenge you have**
I am using my velero instance for current cluster backup and restore as well as cross-aws-account backup and restore, so for ex:

If I have to restore backup from dev to stag , then I have to use an IAM role of dev-account on my staging velero service account, something like this:

**IN-STAGING K8s-CLUSTER**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{dev-aws-account-id}:role/s3
  labels:
    app.kubernetes.io/instance: staging-velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    argocd.argoproj.io/instance: staging-velero
    helm.sh/chart: velero-5.0.2
  name: velero
  namespace: velero
```

But, if I use to backup my same staging cluster resource and in future need to restore in same staging cluster, then I will use IAM role in same staging AWS account , so my service account would be something like that:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{stag-aws-account-id}:role/s3-staging
  labels:
    app.kubernetes.io/instance: staging-velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    argocd.argoproj.io/instance: staging-velero
    helm.sh/chart: velero-5.0.2
  name: velero
  namespace: velero
```

**Describe the solution you'd like**

I would like to annotate my service account  with multiple roles at a time so that I can use same service account for my both scenario

FOR-EX:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{stag-aws-account-id}:role/s3-staging
    eks.amazonaws.com/role-arn: arn:aws:iam::{dev-aws-account-id}:role/s3
  labels:
    app.kubernetes.io/instance: staging-velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    argocd.argoproj.io/instance: staging-velero
    helm.sh/chart: velero-5.0.2
  name: velero
  namespace: velero
```

**Anything else you would like to add:**

It will be good if we can assign something at BSL level , so that we can define credentials using IRSA.

**Environment:**

- helm version (use `helm version`):  
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
chart-version: `5.0.2`
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-2d98532", GitCommit:"222fd0c4adcf243ebeaee986cc0d41a39e570d8f", GitTreeState:"clean", BuildDate:"2023-07-28T16:53:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):
```il58d0@PXCIN-N0545:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
