### ISSUE TITLE
Default upgradeJobResources values are too low and get the UpgradeCRD job OOMKilled

### ISSUE THREAD

**Issue by BaudouinH** [vmware-tanzu/helm-charts#515]
**What steps did you take and what happened:**

Upgrading the Velero Helm chart from velero-5.1.2 to velero-5.1.3 fails:
 the Upgrade CRD job cannot complete due to the pods of the job being OOMKilled when using the chart default resource values.

**What did you expect to happen:**

The upgrade CRD job using the Chart default resource values should not be OOMKilled.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
The job resumed working as intended when I bumped it with the following resource requirements:
```yaml
upgradeJobResources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
```
I am not sure if the OOMKill is due to my environment or because the default values are too low.

I would gladly do the PR if you want, but I am not sure that the values I provided are the best values.

Also, I often hear that setting CPU limits are an anti-pattern and should be avoided, is there a particular reason you set default CPU limit values in this chart instead of making them optional?

**Environment:**

- helm version (use `helm version`):  `3.11.2` (packaged with ArgoCD)
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
Chart version: `velero-5.1.3`
App version: `v1.12.1`
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-gke.900
```
- Kubernetes installer & version:
```
GKE 1.27.4
```
- Cloud provider or hardware configuration:
Google Cloud Platform
- OS (e.g. from `/etc/os-release`):
```
Ubuntu 22.04.3 LTS
```

**Comment by reefland** [comment]
I only had to bump memory a little....
```
upgradeJobResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
```

I have a small 6 node home lab environment and the default values couldn't handle that.
