### ISSUE TITLE
Same metrices.podAnnotaions for deployment and the node-agent-deamonset

### ISSUE THREAD

**Issue by bethmage** [vmware-tanzu/helm-charts#519]
Node-Agent metrics endpoint 8085/metrics is not **reachable via Port: 8085.** 

Problem is the  velero  node-agent-deamonset  and  the  deployment share the same value of the values.yaml.  
 
metrics.podAnnotaions:
```
metrics:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8085"
      prometheus.io/path: "/metrics"
```

https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/node-agent-daemonset.yaml#L42
https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L45
https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L219

**expect to happen:**
As the node-agent metrics endpoint Port is  :8080, Pods metrics endpoint should be configurable via values.yaml.

**Environment:**

- helm version :  v3.12.3
- helm chart version and app version :  Chart version 5.1.3,  appVersion 1.12.1  
- Kubernetes version:  v1.27.7
- Kubernetes installer & version:  v1.27.7
- Cloud provider or hardware configuration:  Rancher v1.27.6+rke2r1
- OS (e.g. from `/etc/os-release`):  Ubuntu 22.04.1 LTS
