### ISSUE TITLE
feat: add support for pushing chart packages to oci (ghcr)

### ISSUE THREAD

**Issue by ishuar** [vmware-tanzu/helm-charts#521]
**Describe the problem/challenge you have**

With Helm OCI being GA, we should also publish the charts to the GitHub Container Registry.

**Describe the solution you'd like**

- Fluxcd-community helm charts and `prometheus-community` helm charts are already using the same solution

reference `fluxcd-community` release workflow:  https://github.com/fluxcd-community/helm-charts/blob/main/.github/workflows/release.yml#L36

Add below steps in [release.yaml](https://github.com/vmware-tanzu/helm-charts/blob/main/.github/workflows/release.yml)

- Permissions to write contents and package by workflow.

```yaml
permissions:
  contents: write
  packages: write
```

in `jobs.<job-name>.steps`

```yaml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi

            helm push "${pkg}" oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts
          done
```

**Anything else you would like to add:**

- Need to check default permissions and access settings for packages modified through workflows properly, GitHub documentation at [here](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#default-permissions-and-access-settings-for-packages-modified-through-workflows)
- OCI registries support content integrity through cryptographic signatures and digests. This ensures that the Helm charts retrieved from the registry are genuine and unaltered.
- [Storing Helm Charts in OCI Registries](https://helm.sh/blog/storing-charts-in-oci/)
