### ISSUE TITLE
Volume snapshots and File System Backup at the same time?

### ISSUE THREAD

**Issue by igorhrcek** [vmware-tanzu/helm-charts#529]
**Describe the problem/challenge you have**
I've added the annotation `backup.velero.io/backup-volumes: data` to all deployments that I want to back up using file system backup. However, the velero is not doing a snapshot of those volumes at all. 

**Describe the solution you'd like**
I would like to configure the velero to do both things - snapshots and file system backups, at the same time. 

**Anything else you would like to add:**
This is how Velero is currently configured:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts chart=velero
      version: 5.1.5
  values:
    deployNodeAgent: true
    credentials:
      useSecret: true
      existingSecret: velero

    configuration:
      backupStorageLocation:
        - name: default
          provider: gcp
          bucket: production-bucket
          credential:
            name: velero
            key: velero-sa.json
      
      volumeSnapshotLocation:
        - name: default
          provider: gcp
          uploaderType: restic
          defaultBackupStorageLocation: default
          credential:
            name: velero
            key: velero-sa.json

    schedules:
      sites:
        enabled: true
        schedule: "0 1 * * *"
        template:
          ttl: "720h"
          storageLocation: default
```

It is not obvious from the chart itself how this can be achieved. If I omit the annotation from one of the deployments, snapshots are being created. 

**Environment:**

- helm version (use `helm version`):  v3.13.1
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 5.1.5 (1.12.2)
- Kubernetes version (use `kubectl version`): 1.24
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Google Kubernetes Engine
- OS (e.g. from `/etc/os-release`):
