### ISSUE TITLE
Apply the resource policy configmap to a yaml with CRD Backup ou Schedule

### ISSUE THREAD

**Issue by andreyolv** [vmware-tanzu/helm-charts#542]
**Describe the problem/challenge you have**
[Documentation](https://velero.io/docs/v1.13/resource-filtering/#resource-policies) only show how to apply resource policy configmap using velero cli. 

How can I apply the resource policy configmap to a yaml with CRD Backup ou Schedule? It's possible?

 Is there any example?

**Environment:**
- helm chart version: 5.2.0
- Kubernetes version: 1.27.3

**Comment by andreyolv** [comment]
I found the answer =D

```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: cluster-dev
  namespace: velero
spec:
  schedule: "0 0 * * *"
  template:
    resourcePolicy:
      kind: configmap
      name: velero-policy
    includedNamespaces:
    - '*'
    includedResources:
    - '*'
    ...
```
