### ISSUE TITLE
Setting backupStorageLocation default field to `false` has no effect

### ISSUE THREAD

**Issue by sherif-fanous** [vmware-tanzu/helm-charts#544]
**What steps did you take and what happened:**

```yaml
configuration:
  backupStorageLocation:
    - bucket: <bucket-name>
      config:
        region: us-east-1
        s3ForcePathStyle: true
        s3Url: <s3-endpoint>
      default: false
      name: default
      provider: aws
```

Using a snippet similar to the above to create a backupStorageLocation that is not the default still results in the backStorageLocation being created with the `default` field set to `true`

I believe the issue is because of the usage of `with` [here ](https://github.com/vmware-tanzu/helm-charts/blob/01ae2d9d6b72989172cda63a289bc3e291178c7b/charts/velero/templates/backupstoragelocation.yaml#L28)

Changing this section to the following should fix this issue

```
{{- if .default }}
default: {{ .default }}
{{- end }}
```

As a result when `default` is set to `false` the `default` field isn't generated by the helm template and somehow/somewhere it seems Velero is assuming that the `default` value should be set to `true`

**What did you expect to happen:**

The backupStorageLocation is created with `default` set to `false`

**Environment:**

- helm version (use `helm version`): `version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): `5.3.0`
- Kubernetes version (use `kubectl version`): `1.28.5`
- Kubernetes installer & version: `k0s`
- OS (e.g. from `/etc/os-release`): `Debian GNU/Linux 12 (bookworm)`
