### ISSUE TITLE
ContainerSecurityContext not correctly applied.

### ISSUE THREAD

**Issue by yesoos** [vmware-tanzu/helm-charts#553]
**What steps did you take and what happened:**
I wanted to set ContainerSecurityContext as in example in valuse.yaml:

```
ContainerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
    add: []
  readOnlyRootFilesystem: true
```

**What did you expect to happen:**
SecurityContext properly set on velero container.

**The output of the following commands will help us better understand what's going on**:
When i dump the yaml of deployed container greping the securitycontext it's set like that (and that's on Pod level not container)

`  securityContext: {}`

**Anything else you would like to add:**
Also tried applying securityContext directly to the container and it does not allow it somehow. SecurityContext works fine for other deployments

**Environment:**

terraform helm provider v2.12.1
helm chart version 5.4.1
kubernetes version 1.27.7
Azure AKS
Ubuntu 22.04
