### ISSUE TITLE
Velero CRD upgrade job failures

### ISSUE THREAD

**Issue by jkoop144** [vmware-tanzu/helm-charts#559]
**What steps did you take and what happened:**
When upgrading the helm chart for Velero, a job is created to upgrade the CRDs for Velero as well. Every deployment we have failures for the CRD job stating that:

```
/tmp/sh: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/sh)
/tmp/sh: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/sh)
```

This comes when the job is starting on an amd64 based node, even though it seems like its looking for aarch64 (ARM). This is happening to all of our helm upgrades for Velero across all of our clusters (each have some different configuration).

**What did you expect to happen:**

The Velero CRD upgrade job to finish properly and the helm upgrade complete.

**The following information will help us better understand what's going on**:

Using helm chart version: 3.1.0

**Environment:**

- Velero version (use `velero version`): 1.10.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): "1.26"
- Kubernetes installer & version: Helm chart version 3.1.0
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
Which Velero version do you want to upgrade to?

**Comment by jkoop144** [comment]
We are not actually upgrading the version of Velero, but just changes some values to be applied. The change in helm values triggers the CRD upgrade.

For the initContainer we are using:

```
initContainers:
  - name: velero-plugin-for-aws
    image: (companyInternalArtifactory)/velero/velero-plugin-for-aws:v1.5.2
    imagePullPolicy: IfNotPresent
```
and our kubectl setup is similar with:
```
kubectl:
  image:
    repository: (companyInternalArtifactory)/bitnami/kubectl
    tag: "${kubectl_version}"
```
