### ISSUE TITLE
Example Prometheus Rule to monitor Velero seems bad

### ISSUE THREAD

**Issue by savar** [vmware-tanzu/helm-charts#562]
This is a copy from https://github.com/vmware-tanzu/velero/issues/7132 therefore please also check the conversation there for further input.

> We saw in our different clusters different reporting even though Velero was affected the same in all three clusters.
> 
> Checking again on the implemented PrometheusRule it is as described in https://github.com/vmware-tanzu/velero/issues/2725 but is this the right choice? The metric velero_backup_attempt_total, as long as no restart happened, is only growing. So using a ratio of failed attempts to an ever growing total should almost make you blind for failures after a long time of "all is good".
> 
> Assuming you run 20 backups per day for a specific schedule and this works fine for a year and your Pod isn't restarting in that time (and that is possible), you would have 7300 successful attempts. If you would do the example query and check for a failure rate of more than 25% you would need 2434 failed attemps before you hit that mark or ~122 days before you even realize that your backups aren't working anymore.
> 
> I am not sure what the best approach would be, but it might be either using an increase() over a shorter time instead of "the whole time the pod is running" or using velero_backup_last_successful_timestamp or other things instead.
> 
> My bug here is mainly: should we change the example (even though it is just a comment) to avoid people simply copy and pasting this and using it as a way to monitor velero backups?

**Comment by virasana** [comment]
Please update the query with one which determines whether backups have failed for the specified duration (in my case, I expect the last daily backup - within a window of 24hr ago - to have succeeded)

**Comment by mc2285** [comment]
Maybe those will work for you guys:

```yaml
- alert: VeleroBackupFailed
  annotations:
    message: Velero backup {{ $labels.schedule }} has failed
  expr: |-
    velero_backup_last_status{schedule!=""} != 1
  for: 45m
  labels:
    severity: warning
- alert: VeleroBackupFailing
  annotations:
    message: Velero backup {{ $labels.schedule }} has been failing for the last 12h
  expr: |-
    velero_backup_last_status{schedule!=""} != 1
  for: 12h
  labels:
    severity: critical
- alert: VeleroNoNewBackup
  annotations:
    message: Velero backup {{ $labels.schedule }} has not run successfuly in the last 30h
  expr: |-
    (
    rate(velero_backup_last_successful_timestamp{schedule!=""}[15m]) <=bool 0
    or
    absent(velero_backup_last_successful_timestamp{schedule!=""})
    ) == 1
  for: 30h
  labels:
    severity: critical
- alert: VeleroBackupPartialFailures
  annotations:
    message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups
  expr: |-
    rate(velero_backup_partial_failure_total{schedule!=""}[25m])
      / rate(velero_backup_attempt_total{schedule!=""}[25m]) > 0.5
  for: 15m
  labels:
    severity: warning
```
They seem to work for me but if they were to be included as an upstream suggestion/default they probably need some testing
