### ISSUE TITLE
BSL shows Unavailable and backup failing

### ISSUE THREAD

**Issue by achar007** [vmware-tanzu/helm-charts#578]
**What steps did you take and what happened:**
here's my velero values.yml file -

cat my-valero.-values.yml | grep -v "^#" | grep -v "  #"
```yml
namespace:
  labels: {}




image:
  repository: velero/velero
  tag: v1.13.2
  pullPolicy: IfNotPresent
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

annotations: {}

secretAnnotations: {}

labels: {}

podAnnotations: {}

podLabels: {}


resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

upgradeJobResources: {}
upgradeCRDsJob:
  extraVolumes: []
  extraVolumeMounts: []
  extraEnvVars: {}


dnsPolicy: ClusterFirst

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

podSecurityContext: {}

containerSecurityContext: {}

lifecycle: {}

priorityClassName: ""

terminationGracePeriodSeconds: 3600

livenessProbe:
  httpGet:
    path: /metrics
    port: http-monitoring
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /metrics
    port: http-monitoring
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

tolerations: []

affinity: {}

nodeSelector: {}

dnsConfig: {}

extraVolumes: []

extraVolumeMounts: []

extraObjects: []

metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s

  service:
    annotations: {}
    labels: {}

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    autodetect: true
    enabled: false
    annotations: {}
    additionalLabels: {}

  nodeAgentPodMonitor:
    autodetect: true
    enabled: false
    annotations: {}
    additionalLabels: {}

  prometheusRule:
    autodetect: true
    enabled: false
    additionalLabels: {}
    spec: []

kubectl:
  image:
    repository: docker.io/bitnami/kubectl
  containerSecurityContext: {}
  resources: {}
  annotations: {}
  labels: {}

upgradeCRDs: true

cleanUpCRDs: false



configuration:
  backupStorageLocation:
  - name: minio
    provider: aws
    bucket: my-mariadb
    caCert:
    prefix:
    default:
    validationFrequency:
    accessMode: ReadWrite
    credential:
      name:
      key:
    config: 
      region: minio
      s3Url: http://10.97.244.44:9000/minio

  volumeSnapshotLocation:
  - name: minio
    provider: aws
    credential:
      name:
      key:
    config: 
      region: minio

  uploaderType:
  backupSyncPeriod:
  fsBackupTimeout:
  clientBurst:
  clientPageSize:
  clientQPS:
  defaultBackupStorageLocation:
  defaultItemOperationTimeout:
  defaultBackupTTL:
  defaultVolumeSnapshotLocations:
  disableControllers:
  disableInformerCache: false
  garbageCollectionFrequency:
  logFormat:
  logLevel:
  metricsAddress:
  pluginDir:
  profilerAddress:
  restoreOnlyMode:
  restoreResourcePriorities:
  storeValidationFrequency:
  terminatingResourceTimeout:
  defaultSnapshotMoveData:
  features:
  namespace:
  extraArgs: []

  extraEnvVars: {}

  defaultVolumesToFsBackup:

  defaultRepoMaintainFrequency:




rbac:
  create: true
  clusterAdministrator: true
  clusterAdministratorName: cluster-admin

serviceAccount:
  server:
    create: true
    name:
    annotations:
    labels:

credentials:
  useSecret: true
  name:
  existingSecret:
  secretContents: 
   cloud: |
     [default]
     aws_access_key_id=Huzf2uG1yoXOwGvm1234
     aws_secret_access_key=1b8xOW9XyP5l40lz7dwzWGfeD2uC74Jf7Tozv
  extraEnvVars: {}
  extraSecretRef: ""

backupsEnabled: true
snapshotsEnabled: true

deployNodeAgent: false

nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  priorityClassName: ""
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  tolerations: []

  annotations: {}

  labels: {}

  useScratchEmptyDir: true

  extraVolumes: []

  extraVolumeMounts: []

  extraEnvVars: {}

  dnsPolicy: ClusterFirst

  podSecurityContext:
    runAsUser: 0

  containerSecurityContext: {}

  lifecycle: {}

  nodeSelector: {}

  affinity: {}

  dnsConfig: {}

schedules: {}

configMaps: {}
```
Installed velero in my Kubernetes cluster -
`helm -n my-velero  install my-velero vmware-tanzu/velero -f my-valero.-values.yml`

velero -n my-velero backup create mariadb-backup --include-namespaces my-mariadb --exclude-namespaces my-velero,default,my-activemq,my-minio --storage-location minio
Backup request "mariadb-backup1" submitted successfully.

```shell
root@control-plane:/home/vboxuser# velero -n my-velero backup-location get
NAME    PROVIDER   BUCKET/PREFIX   PHASE         LAST VALIDATED                  ACCESS MODE   DEFAULT
minio   aws        my-mariadb      Unavailable   2024-05-18 13:40:54 +0530 IST   ReadWrite 
```

**What did you expect to happen:**
```shell
root@control-plane:/home/vboxuser# velero -n my-velero backup-location get
NAME    PROVIDER   BUCKET/PREFIX   PHASE         LAST VALIDATED                  ACCESS MODE   DEFAULT
minio   aws        my-mariadb      Available   2024-05-18 13:40:54 +0530 IST   ReadWrite 
```
**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
I've installed minio installed in my K8s cluster and I'm able to login well using ui and I can see the key and secret. I can see the bucket as well.
helm -n my-minio install my-minio bitnami/minio -f my-minio-values.yml

where values -
```yml
root@control-plane:/home/vboxuser# cat my-minio-values.yml | grep -v "^#" | grep -v "  #"


global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  compatibility:
    openshift:
      adaptSecurityContext: auto

nameOverride: ""
namespaceOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
kubeVersion: ""
clusterDomain: cluster.local
extraDeploy: []

image:
  registry: docker.io
  repository: bitnami/minio
  tag: 2024.5.10-debian-12-r2
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
clientImage:
  registry: docker.io
  repository: bitnami/minio-client
  tag: 2024.5.9-debian-12-r2
  digest: ""
mode: standalone
auth:
  rootUser: admin
  rootPassword: "mypassword"
  existingSecret: ""
  rootUserSecretKey: "Huzf2uG1yoXOwGvm1234"
  rootPasswordSecretKey: "1234b8xOW9XyP5l40lz7dwzWGfeD2uC74Jf7Tozv"
  forcePassword: false
  useCredentialsFiles: false
  forceNewKeys: false
defaultBuckets: "my-test, my-mariadb, dbaas"
disableWebUI: false
tls:
  enabled: false
  autoGenerated: false
  existingSecret: ""
  mountPath: ""
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
command: []
args: []

schedulerName: ""
terminationGracePeriodSeconds: ""
deployment:
  updateStrategy:
    type: Recreate
statefulset:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  replicaCount: 4
  zones: 1
  drivesPerNode: 1
provisioning:
  enabled: false
  schedulerName: ""
  nodeSelector: {}
  podLabels: {}
  podAnnotations: {}
  command: []
  args: []
  extraCommands: []
  extraVolumes: []
  extraVolumeMounts: []
  resourcesPreset: "nano"
  resources: {}
  policies: []
  users: []
  usersExistingSecrets: []
  groups: []
  buckets: []
  config: []
  podSecurityContext:
    enabled: false
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  cleanupAfterFinished:
    enabled: false
    seconds: 600
  networkPolicy:
    enabled: false
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
automountServiceAccountToken: false
hostAliases: []
containerPorts:
  api: 9000
  console: 9001
podSecurityContext:
  enabled: false
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"
containerSecurityContext:
  enabled: false
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
podLabels: {}
podAnnotations: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
priorityClassName: ""
runtimeClassName: ""
resourcesPreset: "micro"
resources: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
startupProbe:
  enabled: false
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 60
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
lifecycleHooks: {}
extraVolumes: []
extraVolumeMounts: []
initContainers: []
sidecars: []

service:
  type: LoadBalancer
  ports:
    api: 9000
    console: 9001
  nodePorts:
    api: ""
    console: ""
  clusterIP: ""
  loadBalancerIP: "192.168.56.184"
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  extraPorts: []
  annotations: {}
  headless:
    annotations: {}
ingress:
  enabled: false
  apiVersion: ""
  ingressClassName: ""
  hostname: minio.local
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-console
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
apiIngress:
  enabled: false
  apiVersion: ""
  ingressClassName: ""
  hostname: minio.local
  path: /
  pathType: ImplementationSpecific
  servicePort: minio-api
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  extraRules: []
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true
  extraIngress: []
  extraEgress: []
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}

persistence:
  enabled: true
  storageClass: "nfs-client"
  mountPath: /bitnami/minio/data
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
  existingClaim: ""

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r21
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "nano"
  resources: {}
  containerSecurityContext:
    seLinuxOptions: {}
    runAsUser: 0

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}

pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""
metrics:
  prometheusAuthType: public
  serviceMonitor:
    enabled: false
    namespace: ""
    labels: {}
    jobLabel: ""
    paths:
      - /minio/v2/metrics/cluster
      - /minio/v2/metrics/node
    interval: 30s
    scrapeTimeout: ""
    metricRelabelings: []
    relabelings: []
    honorLabels: false
    selector: {}
    apiVersion: ""
    tlsConfig: {}
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []
```

velero pod log -
```shell
time="2024-05-18T07:35:24Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"minio\" is unavailable: rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 17D0850741E9E650, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AllAccessDisabled: All access to this resource has been disabled.)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"
time="2024-05-18T07:35:24Z" level=warning msg="There is no existing BackupStorageLocation set as default. Please see `velero backup-location -h` for options." controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:187"
time="2024-05-18T07:36:14Z" level=error msg="Error listing backups in backup store" backupLocation=my-velero/minio controller=backup-sync error="rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 17D08512E33B0A95, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AllAccessDisabled: All access to this resource has been disabled." error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:318" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:108"
time="2024-05-18T07:36:24Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=my-velero/minio controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:141"
time="2024-05-18T07:36:24Z" level=error msg="fail to validate backup store" backup-storage-location=my-velero/minio controller=backup-storage-location error="rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 17D085153A287B6A, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AllAccessDisabled: All access to this resource has been disabled." error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:202" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:144"
time="2024-05-18T07:36:24Z" level=info msg="BackupStorageLocation is invalid, marking as unavailable" backup-storage-location=my-velero/minio controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:120"
time="2024-05-18T07:36:24Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"minio\" is unavailable: rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 17D085153A287B6A, HostID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, api error AllAccessDisabled: All access to this resource has been disabled.)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"
time="2024-05-18T07:36:24Z" level=warning msg="There is no existing BackupStorageLocation set as default. Please see `velero backup-location -h` for options." controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:187"
```

**Environment:**

- helm version (use `helm version`): 
helm version
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}

- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
helm list -n my-velero
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
my-velero	my-velero	4       	2024-05-18 13:04:08.789684363 +0530 IST	deployed	velero-6.4.0	1.13.2    

helm list -n my-minio
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
my-minio	my-minio 	2       	2024-05-18 12:50:26.822495626 +0530 IST	deployed	minio-14.4.2	2024.5.10  

- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

- OS (e.g. from `/etc/os-release`):
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
