### ISSUE TITLE
How to add multiple plugin in the charts

### ISSUE THREAD

**Issue by WRKT** [vmware-tanzu/helm-charts#605]
Hello, 
I am currently developping a custom restoreItemAction for velero to solve one of my problem, and I have a question of how can I add it to the current values without impacting the provider plugin:

```yaml
initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          - name: velero-custom-plugins
            image: registry/velero/velero-custom-plugins:1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: custom-plugins
extraVolumes:
          - custom-plugins
```

Will this override the velero plugin for aws ? or am I doing right ?
