### ISSUE TITLE
Azure deployment failed because it does not match velero cli installation

### ISSUE THREAD

**Issue by HamzaK8s** [vmware-tanzu/helm-charts#61]
I deployed velero on Azure using the helm chart. Everything looks good
```
kubectl get po -n velero 
NAME                      READY   STATUS    RESTARTS   AGE
restic-bjc7m              1/1     Running   0          28m
restic-sz8xw              1/1     Running   0          28m
restic-xhp7w              1/1     Running   0          28m
velero-6b688bdd4c-cjhks   1/1     Running   0          28m
 ```
But while running  `velero backup` command, I'm getting some weird errors as follows:

```time="2020-02-13T14:18:04Z" level=error msg="Error backing up item" backup=velero/ark-test-ns4-1581603471 error="pod volume backup failed: error setting restic cmd env: error getting azure restic env vars: unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=nginx-deployment-864c87c896-8zfgs namespace=ark-test-ns4-1581603471 resource=pods```

and the problem was the `envFrom` 
```
          {{- if eq $provider "azure" }}
          envFrom:
            - secretRef:
                name: {{ include "velero.secretName" . }}
          {{- end }}
```
Comparing the velero cli installation with the output of helm chart is a bit different concerning the way we use the cloud-credentials 

with veleo cli we don't use the `envFrom` field 
```
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
  spec:
    selector:
      matchLabels:
        deploy: velero
    strategy: {}
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8085"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          component: velero
          deploy: velero
      spec:
        containers:
        - args:
          - server
          command:
          - /velero
          env:
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LD_LIBRARY_PATH
            value: /plugins
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.2.0
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: metrics
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        initContainers:
        - image: velero/velero-plugin-for-microsoft-azure:v1.0.0
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-microsoft-azure
          resources: {}
          volumeMounts:
          - mountPath: /target
            name: plugins
        restartPolicy: Always
        serviceAccountName: velero
        volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
```
Deleting manually it fixes the problem.
