### ISSUE TITLE
Velero pre-upgrade job missing image pull secret configuration

### ISSUE THREAD

**Issue by cwstrommer** [vmware-tanzu/helm-charts#622]
**What steps did you take and what happened:**

I am attempting to install Velero with Helm chart and the following values:

```
image:
  repository: <private repo>
  imagePullSecrets:
  - <secret for private repo>
kubectl:
  image:
    repository: <private repository>
```

The Velero pre-upgrade job fails with `Init:ImagePullBackOff` because the chart has no configuration option for setting image pull secrets for the `kubectl` job pods.

In both cases for Velero and `kubectl`, <private repository> refers to a private container registry where we host copies of the images used by the Velero chart.  This setup is needed to meet compliance requirements in our environment, we are not allowed to pull directly into the cluster from public repositories.

**What did you expect to happen:**

Be able to set the image pull secret for the `kubectl` job, either as a separate setting for the Velero container or via a global setting for all pods, e.g.

```
kubectl:
  image:
    imagePullSecrets:
```
or
```
global:
  imagePullSecrets:
```

**Environment:**

- helm chart version and app version: 7.2.1, 1.14.1

(other requested environment information not relevant to issue)
