### ISSUE TITLE
Cleanup maintenance job pods in Competed state

### ISSUE THREAD

**Issue by insider89** [vmware-tanzu/helm-charts#628]
**What steps did you take and what happened:**
Maintenance Job running very frequently and we have a lot of pod in Completed state. I don't see any parameters I can provide to cleanup it.
<img width="1847" alt="Screenshot 2024-11-15 at 14 34 22" src="https://github.com/user-attachments/assets/df022a84-6345-4b98-8092-f4b7288195ab">

**What did you expect to happen:**
Helm chart should allow to set `ttlSecondsAfterFinished` parameter for maintenance job.

**The output of the following commands will help us better understand what's going on**:
```
repositoryMaintenanceJob:
    requests:
    #   cpu: 500m
    #   memory: 512Mi
    limits:
    #   cpu: 1000m
    #   memory: 1024Mi
    # Number of latest maintenance jobs to keep for each repository
    latestJobsCount: 3
```

**Anything else you would like to add:**
Add new `ttlSecondsAfterFinished` to the repositoryMaintenanceJob would be helm to keep env clean.

**Environment:**

- helm version (use `helm version`):  3.16
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 8.0.0
- Kubernetes version (use `kubectl version`): 1.30.5
- Kubernetes installer & version:  1.30.5
- Cloud provider or hardware configuration: GKE/AWS/Azure
- OS (e.g. from `/etc/os-release`): Linux
