### ISSUE TITLE
BackupStorageLocation.velero.io "default" is invalid

### ISSUE THREAD

**Issue by lsacco-nutreense** [vmware-tanzu/helm-charts#631]
**What steps did you take and what happened:**
A simply ran helm with my values file and get this output:
```
helm install velero vmware-tanzu/velero \
  --namespace velero \
  --create-namespace \
  --values velero-values-nonprod.yaml

Error: INSTALLATION FAILED: 2 errors occurred:
	* BackupStorageLocation.velero.io "default" is invalid: [spec.objectStorage.bucket: Required value, spec.provider: Required value]
	* VolumeSnapshotLocation.velero.io "default" is invalid: spec.provider: Required value
```

Here's what my values file looks like:
```
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocations:
    - name: default
      spec:
        provider: aws
        objectStorage:
          bucket: prod-eks-backup
        config:
          region: us-west-2
          profile: "default" # I've tried with and w/o this
  volumeSnapshotLocations:
    - name: default
      spec:
        provider: aws
        config:
          region: us-west-2
          profile: "default" # I've tried with and w/o this

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: [arn-to-my-iam-role]
  create: true
  name: velero-server
credentials:
  useSecret: false

```

**What did you expect to happen:**

I wasn't expecting to see this error. I've tried multiple variations of my values.yaml and to no avail.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): `version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 
```
helm list -n velero
NAME  	NAMESPACE	REVISION	UPDATED                             	STATUS	CHART       	APP VERSION
velero	velero   	1       	2024-11-24 14:51:21.144488 -0800 PST	failed	velero-8.0.0	1.15.0
```
- Kubernetes version (use `kubectl version`):`v1.30.3`
- Kubernetes installer & version: `brew`
- Cloud provider or hardware configuration: `AWS EKS v1.230`
- OS (e.g. from `/etc/os-release`): `AWS Linux 2023`

**Comment by digitalperception** [comment]
@lsacco-nutreense I have successfully installed it and initially I was also getting a similar error.

Here is my configuration: 

  ```
 configuration:
      backupStorageLocation:
      - name: minio-backup
        provider: aws
        bucket: xyz-velero-backup
        default: true
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: https://xyz.com
          publicUrl: https://xyz.com
```
You should make 2 changes in your values: 1: replace `backupStorageLocation:` with `backupStorageLocations:` because in the original values.yaml file it is singular. 2: use a custom value like `xyz-backup` for `name` field instead of `default`. It has worked in my case.
