### ISSUE TITLE
Allow extraEnvVars that use valueFrom

### ISSUE THREAD

**Issue by ejstreet** [vmware-tanzu/helm-charts#633]
**Describe the problem/challenge you have**
The chart as it is currently configured does not allow passing `extraEnvVars` that use a `valueFrom`, it enforces `name` and `value` inputs only using a range.

**Describe the solution you'd like**
Allow the `extraEnvVars` to support all valid `env` inputs e.g.
```yaml
extraEnvVars:
  - name: MY_VAR_FROM_FIELD_REF
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['my_label']
```

**Environment:**
- helm version:  `3`
- helm chart version and app version: `8.1.0`/`1.15.0`
- Kubernetes version: `1.31`
