### ISSUE TITLE
ArgoCD/Helm does not create BackupStorageLocation or VolumeSnapshotLocation resources.

### ISSUE THREAD

**Issue by darnone** [vmware-tanzu/helm-charts#646]
**What steps did you take and what happened:**
I am running a helm install with a configuration that has worked on the past but the backupstoragelocation and volumesnapshotlocation resources are not deployed. If I perform a helm template with my values files, the generate manifest are incorrect:

generated manifest:
```
---
# Source: velero/templates/backupstoragelocation.yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: default
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: my-velero
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-8.4.0
spec:
  credential:
  provider: 
  accessMode: ReadWrite
  objectStorage:
    bucket:
---
# Source: velero/templates/volumesnapshotlocation.yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: default
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: my-velero
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-8.4.0
spec:
  credential:
  provider:
```

I you notice, the name is still default and the provider is empty.

values:
```
configuration:
  features: EnableCSI
  uploaderType: kopia
  backupStorageLocation:
  - name: velero-backup-storage-location
    bucket: <bucket-name>
    default: true
    provider: aws
    config:
      region: us-east-1
  volumeSnapshotLocation:
  - name: velero-volume-storage-location
    provider: aws
    config:
      region: us-east-1
```

**What did you expect to happen:**

I expected the backupstoragelocation and volumesnapshotlocation resources to be created

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

log shows:

time="2025-02-25T22:11:11Z" level=warning msg="Velero node agent not found; pod volume backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:650"
time="2025-02-25T22:11:11Z" level=warning msg="Failed to set default backup storage location at server start" backupStorageLocation=default error="backupstoragelocations.velero.io \"default\" not found" logSource="pkg/cmd/server/server.go:492"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I am deploying this with argocd cd but get the same result with helm even though I have a running install of velero in another cluster with helmfile
**Environment:**

- helm version (use `helm version`):  v3.17.1
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): chart:8.4.0, app: 1.15.2
- Kubernetes version (use `kubectl version`): 1.30.9
- Kubernetes installer & version: asdf 0.16.4
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Client Mac, AWS EKS node AWS optimized Linus 2

**Comment by ts-kravits** [comment]
https://github.com/vmware-tanzu/velero/issues/8701#issuecomment-2682663006

I had the same issue and per this comment added velero to the top, so for you I would try this.
```
velero:
  configuration:
    features: EnableCSI
    uploaderType: kopia
    backupStorageLocation:
    - name: velero-backup-storage-location
      bucket: <bucket-name>
      default: true
      provider: aws
      config:
        region: us-east-1
    volumeSnapshotLocation:
    - name: velero-volume-storage-location
      provider: aws
      config:
        region: us-east-1
```
