### ISSUE TITLE
Service name cannot be named

### ISSUE THREAD

**Issue by hongbo-miao** [vmware-tanzu/helm-charts#652]
**What steps did you take and what happened:**

When I deploy by

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-hm-velero
  namespace: production-hm-argo-cd
  labels:
    app.kubernetes.io/name: hm-velero
spec:
  project: production-hm
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    # https://artifacthub.io/packages/helm/vmware-tanzu/velero
    targetRevision: 8.5.0
    chart: velero
    helm:
      releaseName: hm-velero
      values: |
        # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
        ---
        image:
          repository: harbor.hongbomiao.com/docker-hub-proxy-cache/velero/velero
        serviceAccount:
          create: true
          name: my-cool-velero
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::272394222652:role/VeleroRole-hm-velero
        initContainers:
          - name: aws-plugin
            image: velero/velero-plugin-for-aws:v1.11.1
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
            - name: aws-backup
              provider: aws
              bucket: production-hm-velero-bucket
              accessMode: ReadWrite
              config:
                region: us-west-2
          volumeSnapshotLocation:
            - name: aws-snapshot
              provider: aws
              config:
                region: us-west-2
  destination:
    namespace: production-hm-velero
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
```

The service name created is called `hm-velero-server` instead of `my-cool-velero` I named.

**What did you expect to happen:**

I expect service account name called `hm-velero-server`

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**

None.

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`): 	1.32
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`):

**Comment by hongbo-miao** [comment]
My bad, it should be 

```yaml
serviceAccount:
  server:
    create: true
    name: my-cool-velero
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::272394222652:role/VeleroRole-hm-velero
```

I missed `server:` inside. 🥲
