### ISSUE TITLE
Inconsistent label format in Velero chart causing warnings and errors

### ISSUE THREAD

**Issue by tpanza** [vmware-tanzu/helm-charts#653]
**What steps did you take and what happened:**

The current implementation of namespace labels in the Velero Helm chart causes warnings during helm upgrade/install operations and leads to errors when attempting to use standard YAML map format for labels.

When using the chart-expected format for namespace labels:
```yaml
namespace:
  labels:
    - key: pod-security.kubernetes.io/enforce
      value: privileged
    - key: pod-security.kubernetes.io/enforce-version
      value: latest
    # additional labels...
```

This generates the following warning:
```
coalesce.go:298: warning: cannot overwrite table with non table for velero.namespace.labels (map[])
```

When attempting to use standard Kubernetes/Helm YAML map format for labels:
```yaml
namespace:
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    # additional labels...
```

This results in deployment failure with error:
```
Error: UPGRADE FAILED: template: velero/templates/label-namespace/labelnamespace.yaml:34:63: executing "velero/templates/label-namespace/labelnamespace.yaml" at <.key>: can't evaluate field key in type interface {}
```

**What did you expect to happen:**

Be able to apply the labels without warnings or errors

The chart should either:
1. Use standard YAML map format for labels (preferred)
2. Properly document that labels must be provided in list format with key/value pairs
3. Handle both formats correctly without warnings or errors

**Environment:**

- helm version (use `helm version`):  `version.BuildInfo{Version:"v3.17.1", GitCommit:"980d8ac1939e39138101364400756af2bdee1da5", GitTreeState:"clean", GoVersion:"go1.23.5"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): `velero-8.6.0    1.15.2`
- Kubernetes version (use `kubectl version`): `Client Version: v1.31.5+rke2r1, Kustomize Version: v5.4.2, Server Version: v1.31.5+rke2r1`
- Kubernetes installer & version: RKE2 (Rancher Kubernetes Engine 2), v1.31.15
- Cloud provider or hardware configuration: non-cloud
- OS (e.g. from `/etc/os-release`): `Red Hat Enterprise Linux 9.5 (Plow)`
