### ISSUE TITLE
`latestJobsCount` can't be numeric zero

### ISSUE THREAD

**Issue by cometship** [vmware-tanzu/helm-charts#681]
**What steps did you take and what happened:**
Setting `configuration.repositoryMaintenanceJob.latestJobsCount = 0` does not work because of [this](https://github.com/vmware-tanzu/helm-charts/blob/5d02d5bd2fb26e921ecda60631ec0cb5d9cf6a04/charts/velero/templates/deployment.yaml#L195). The `with` excludes the block if the value is a numeric zero (`0`).

**What did you expect to happen:**
It to work with numeric zero.

**Possible fix (untested):**
```yml
{{- if hasKey . "latestJobsCount" }}
- --keep-latest-maintenance-jobs={{ .latestJobsCount }}
{{- end }}
```

_Edit: modify possible fix and remove workaround that's now non functional_

**Comment by cometship** [comment]
Fixed in `v10.0.4`

**Comment by cometship** [comment]
I tried it with:

```yaml
configuration:
  repositoryMaintenanceJob:
    repositoryConfigData:
      global:
        keepLatestMaintenanceJobs: 0
```

But it still keeps the jobs. 

The arg `--repo-maintenance-job-configmap=velero-repo-maintenance` gets applied to the deployment though. And the configmap is also created.
