### ISSUE TITLE
Update 10.0.3 to 10.0.4 results in schema validation error when volumeSnapshotLocation.config is not provided

### ISSUE THREAD

**Issue by rafal11ck** [vmware-tanzu/helm-charts#693]
**What steps did you take and what happened:**
update from 10.0.3 to 10.0.4

**What did you expect to happen:**

Helm to not fail

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**

flux local log
```
Pulled: ghcr.io/vmware-tanzu/charts/velero:10.0.4
E           Digest: sha256:0a4b3f620b362206a5a728381081d5c6adbdabef83070c7d705b61e2eae16ea1
E           Error: values don't meet the specifications of the schema(s) in the following chart(s):
E           velero:
E           - configuration.volumeSnapshotLocation.0: config is required

```

volumeSnapshotLocation.config is optional, https://velero.io/docs/v1.16/api-types/volumesnapshotlocation/, 

part of helm values was as following:

```yaml
      volumeSnapshotLocation:
        - name: default
          provider: velero.io/csi
``` 

changing it to 

```yaml
      volumeSnapshotLocation:
        - name: default
          provider: velero.io/csi
          config: {}
```

made it work

I merged it anyway, got same error. 

**Environment:**

- helm version (use `helm version`): fluxcd 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-10.0.5   1.16.1
- Kubernetes version (use `kubectl version`): Client Version: v1.33.1, Kustomize Version: v5.6.0 Server Version: v1.33.1
- Kubernetes installer & version: talos 1.10.3
- Cloud provider or hardware configuration: irrelevant, bare metal 3 nodes
- OS (e.g. from `/etc/os-release`): talos
