### ISSUE TITLE
Unable to set insecureSkipTLSVerify for backupStorageLocation

### ISSUE THREAD

**Issue by r-catania** [vmware-tanzu/helm-charts#77]
the flag  insecureSkipTLSVerify was added to velero under PR https://github.com/vmware-tanzu/velero/pull/1769 .
When setting the flag under backupStorageLocation it is currently ignored.

**Comment by jenting** [comment]
Hi @r-catania, I saw the PR #82 includes a fix with this, could you please test it again?

Furthermore, Velero 1.4 and helm chart #128 includes passing custom CA to backupStorageLocation.

**Comment by jenting** [comment]
I'm using helm3 to run `helm template` with helm chart version `2.12.14`, and I could see the `insecureSkipTLSVerify: true` in BackupStorageLocation.

```
helm template velero \
  --create-namespace \
  --set-file credentials.secretContents.cloud=credentials-velero \
  --set configuration.provider=aws \
  --set configuration.backupStorageLocation.name=default \
  --set configuration.backupStorageLocation.bucket=velero \
  --set configuration.backupStorageLocation.config.region=minio \
  --set configuration.backupStorageLocation.config.s3ForcePathStyle=true \
  --set configuration.backupStorageLocation.config.s3Url=https://minio.velero.svc.cluster.local:9000 \
  --set configuration.backupStorageLocation.config.insecureSkipTLSVerify=true \
  --set initContainers[0].name=velero-plugin-for-aws \
  --set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
  --set initContainers[0].volumeMounts[0].mountPath=/target \
  --set initContainers[0].volumeMounts[0].name=plugins \
  .
```

```
# Source: velero/templates/backupstoragelocation.yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-2.12.14
spec:
  provider: aws 
  objectStorage:
    bucket: velero
  config:
    insecureSkipTLSVerify: true
    region: minio
    s3ForcePathStyle: true
    s3Url: https://minio.velero.svc.cluster.local:9000
    s3ForcePathStyle: "true"
```
