### ISSUE TITLE
Support environment variables from secrets

### ISSUE THREAD

**Issue by james-emerton** [vmware-tanzu/helm-charts#87]
I'm currently in the process of using this chart to deploy Velero for a cluster running on DigitalOcean. To support volume snapshots, I need to provide an environment variable `DIGITALOCEAN_TOKEN`. This chart currently only supports simple key/value environment variables, but I'd like to use `secretKeyRef`.

I propose that another key is added to `values.yaml` (to maintain compatibility) that simply injects it's contents into `env` using `toYaml`.

eg:
```
configuration:
  env:
    - name: DIGITALOCEAN_TOKEN
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: digitalocean_token
```
