### ISSUE TITLE
[Azure] Error installing helm chart on Azure

### ISSUE THREAD

**Issue by koustubhg** [vmware-tanzu/helm-charts#91]
I have the following credentials file `azure-storage-creds`
```
AZURE_SUBSCRIPTION_ID=<my-id>
AZURE_TENANT_ID=<tenant-id>
AZURE_CLIENT_ID=<client-id>
AZURE_CLIENT_SECRET=<client-secret>
AZURE_RESOURCE_GROUP=<resource group>
AZURE_CLOUD_NAME=AzurePublicCloud
```

`kubectl -n dev create secret generic mysecret --from-file=cloud=azure-storage-creds`

`cat velero/dev-override.yaml`
```
initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

image:
  repository: velero/velero
  tag: v1.3.1
  pullPolicy: IfNotPresent

configuration:
  provider: azure
  backupStorageLocation:
    name: azure
    bucket: my-blob-container
  volumeSnapshotLocation:
    name: azure

credentials:
  useSecret: true
  existingSecret: mysecret
```

I installed velero using this command:
`helm install --name=velero --namespace=dev -f velero/dev-override.yaml vmware-tanzu/velero`

I get the following error in the logs:

```
time="2020-04-04T07:25:47Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"                               
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to get all required config values: the following keys do not have values: resourceGroup, storageAccount
```

Where do I need to specify the above values?

**Comment by alikhtag** [comment]
Following override yaml is working for us
```yaml

configuration:
  provider: azure
  # Location of Velero Backups, which is a `velero-backups` blob container
  backupStorageLocation:
    bucket: velero-backups
    config:
      resourceGroup: velero-backups
      subscriptionId: <subscription-id>
      storageAccount: <backup-storage-acc-name>
  # Location of persistent volume/disk snapshots,
  # which is `velero-backups` resource group
  volumeSnapshotLocation:
    config:
      apiTimeout: "600s"
      resourceGroup: velero-backups
      subscriptionId: <subscription-id>

credentials:
  useSecret: true
  # Use predefined deployed secret
  existingSecret: velero-cloud-credentials

initContainers:
# Set up Azure Velero plugin
  - name: velero-plugin-for-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
```
One thing to note, we use `ServicePrincipal` for RBAC, but from looking at your `azure-storage-creds` credentials file you seem to use it too.
